### ISSUE TITLE
Bad practices related to security in jitsi images 

### ISSUE THREAD

**Issue by Ais8Ooz8** [jitsi/docker-jitsi-meet#1011]
For example, in Kubernetes it would be normal to run containers with such directives:

```
securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
```
Various DevSecOps tools check these directives, for example https://docs.kics.io/queries/kubernetes-queries

But jitsi images prevent such important settings from being applied 

Perhaps this needs revision? Otherwise, security is seriously affected

How can we avoid using https://github.com/just-containers/s6-overlay? It seems we need to keep something like this in our mind https://github.com/GoogleContainerTools/distroless and try to move in this direction
