### ISSUE TITLE
jitsi-meet.cfg.lua changes automatically after docker compose

### ISSUE THREAD

**Issue by shakeeb91** [jitsi/docker-jitsi-meet#1026]
We have deployed jitsi/prosody:latest via docker-compose.yml and whenever we restart it reverts our custom configuration file. Below is the docker-compose:

```
version: '3.5'

services:
  prosody:
    container_name: prosody
    image: jitsi/prosody:latest
    ports:
      - 5222:5222
      - 5269:5269
      - 5347:5347
      - 5280:5280
    volumes:
      - /etc/docker-prosody/config:/config
      - /etc/docker-prosody/prosody-plugins-custom:/prosody-plugins-custom
    restart: on-failure
    environment:
      - AUTH_TYPE=jwt
      - JWT_APP_ID=jitsimeet@domain.com
      - JWT_APP_SECRET=test123
      - XMPP_DOMAIN=domain.com
      - XMPP_AUTH_DOMAIN=auth.domain.com
      - XMPP_SERVER=domain.com
      - XMPP_INTERNAL_MUC_DOMAIN=internal.auth.domain.com
      - XMPP_MUC_DOMAIN=conference.domain.com
      - JVB_COMPONENT_SECRET=test123
      - JVB_AUTH_USER=jvb
      - JVB_AUTH_PASSWORD=test123
      - JICOFO_COMPONENT_SECRET=test123
      - JICOFO_AUTH_USER=focus
      - JICOFO_AUTH_PASSWORD=test123
      - ENABLE_AUTH=1
```
    
     
We have placed prosody-ourfile.conf.lua inside /etc/docker-prosody/config/conf.d/ but after restarting /etc/docker-prosody/config/conf.d/jitsi-meet.cfg.lua shows a default configuration and it is not reading our: prosody-ourfile.conf.lua 
How we can use our file basically our file does contain TURN server configuration and it is not working. 

Issue: We need to run the TURN server
