### ISSUE TITLE
Failed to connect to system bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

### ISSUE THREAD

**Issue by suharevA** [jitsi/docker-jitsi-meet#1442]
Why is there such an error when assembling jibri latest 7882.
I collect like this
make build_jibri

```
[pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
```
How to turn it off?
If I install from docker hub. There is no such error. What's the Difference?

**Comment by saghul** [comment]
Have you made any changes to the container?

Does it not start?

Some of the PulseAudio errors can actually be ignored.

**Comment by suharevA** [comment]
Contributed. Added python3 and pip install requests

**Comment by saghul** [comment]
Please share your changes and the full log when the container starts.

**Comment by saghul** [comment]
What env vars and values are you passing?

**Comment by suharevA** [comment]
```
data:
  CONFIG: ~/jibri
  DISPLAY: :0
  JIBRI_BREWERY_MUC: jibribrewery
  JIBRI_FINALIZE_RECORDING_SCRIPT_PATH: /config/finalize.sh
  JIBRI_LOGS_DIR: /config/logs
  JIBRI_RECORDER_PASSWORD: pass
  JIBRI_RECORDER_USER: jibri_usr
  JIBRI_RECORDING_DIR: /config/recordings
  JIBRI_STRIP_DOMAIN_JID: muc
  JIBRI_XMPP_PASSWORD: pass
  JIBRI_XMPP_USER: jibri_usr
  LOG_LEVEL: debug
  PUBLIC_URL: https://domen
  TZ: Europe/Moscow
  XMPP_AUTH_DOMAIN: auth.domen
  XMPP_DOMAIN: domen
  XMPP_INTERNAL_MUC_DOMAIN: internal.domen
  XMPP_RECORDER_DOMAIN: recorder.domen
  XMPP_SERVER: domen
```
