### ISSUE TITLE
not getting  recordingLinkAvailable event

### ISSUE THREAD

**Issue by iasbm** [jitsi/docker-jitsi-meet#1533]
We have installed JITSI (including JIBRI) on K8S cluster and we are able to successfully record the calls.
But as per `recordingLinkAvailable` mentioned [here ](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe-events#recordinglinkavailable) we have registered for the event `recordingLinkAvailable` and expect to receive with notification with Recorded file link.
But we are not getting any notification for that.  
Our customized JIBRI configuration in values.custom.yaml is 
```
### JIBRI specific configurations
jibri:
  enabled: true

  replicaCount: 1

  # If replicate count > 1, need set on true. Persistent Jibri services turn off
  singleUseMode: false

  # Add mode deployment or statefulset
  mode: "statefulset"

  # Persistence pvc per pod
  persistence:
    enabled: false
    accessModes:
      - ReadWriteOnce
```

are we missing any further JIBRI config settings to be customized or do we need to write a `finalize.sh` to get that event notification.
I think the finalizeScript.sh to let JIBRI execute the script, after every recording, to upload the file to our custom location by using that `finalize.sh`

So not sure why we are not getting the `recordingLinkAvailable` event triggered?
Any help is appreciated.
