### ISSUE TITLE
jitsi not use given stun server

### ISSUE THREAD

**Issue by Fmajor** [jitsi/docker-jitsi-meet#1568]
I start a jitsi server using docker, It has been running for several months without problems.
But today it suddenly stop to work. All users can not get the video and audio streams from others.

when I open devtool from the browser and search for STUN logs, i got
```
2023-06-26T08:29:23.856Z [modules/xmpp/xmpp.js] <_initStrophePlugins>:  P2P STUN servers:  
Array [ {…} ]
​0: Object { urls: "stun:meet-jit-si-turnrelay.jitsi.net:443" }
```

It seems that jitsi do not use my STUN settings and just use the default STUN server

I have set the environments related with TURN server like
```
TURN_CREDENTIALS=<the-credentials>
TURNS_HOST=<our-turn-server>
TURNS_PORT=<our-turn-server-port>
```
I check our turn server with
```
turnutils_uclient -p <our-turn-server-port> -u jitsi -W <the-credentials> -T <our-turn-server>
```
and get no error

I can see the live config files
 ```
# in config/jvb/jvb.conf
ice4j {
    harvest {
        mapping {
            stun {
addresses = [ "<our-turn-server>: <our-turn-server-port>" ]
}
            static-mappings = [
{
                    local-address = "10.10.234.5"
                    public-address = ""
                    name = "ip-0"
                },
]
        }
    }
}
# in config/prosody/config/conf.d/jitsi-meet.conf.lua
external_service_secret = "<the-credentials>";
external_services = {
        { type = "turns", host = "<our-turn-server>", port = <our-turn-server>, transport = "tcp", secret = true, ttl = 86400, algorithm = "turn" }
};
 ```
but It seems that jitsi do not use the setting TURN server, but select to use the default stun:meet-jit-si-turnrelay.jitsi.net:443

**How to make jitsi to use the give STUN server again?**

here is docker-comose, the full config file is too large, I just paste the config about prosody
```
version: '3.9'

services:
  # other servers
  prosody:
    container_name: ${DNAME}-prosody
    image: ${IMAGE_prosody}
    restart: ${RESTART_POLICY}
    expose:
      - '5222'
      - '5347'
      - '5280'
    volumes:
      - ${CONFIG}/prosody/config:/config:Z
      - ${CONFIG}/prosody/prosody-plugins-custom:/prosody-plugins-custom:Z
    environment:
      - AUTH_TYPE
      - DISABLE_POLLS
      - ENABLE_AUTH
      - ENABLE_AV_MODERATION
      - ENABLE_BREAKOUT_ROOMS
      - ENABLE_GUESTS
      - ENABLE_LOBBY
      - ENABLE_XMPP_WEBSOCKET
      - GLOBAL_CONFIG
      - GLOBAL_MODULES
      - JIBRI_RECORDER_USER
      - JIBRI_RECORDER_PASSWORD
      - JIBRI_XMPP_USER
      - JIBRI_XMPP_PASSWORD
      - JICOFO_AUTH_USER
      - JICOFO_AUTH_PASSWORD
      - JICOFO_COMPONENT_SECRET
      - JIGASI_XMPP_USER
      - JIGASI_XMPP_PASSWORD
      - JVB_AUTH_USER
      - JVB_AUTH_PASSWORD
      - JWT_APP_ID
      - JWT_APP_SECRET
      - JWT_ACCEPTED_ISSUERS
      - JWT_ACCEPTED_AUDIENCES
      - JWT_ASAP_KEYSERVER
      - JWT_ALLOW_EMPTY
      - JWT_AUTH_TYPE
      - JWT_TOKEN_AUTH_MODULE
      - LOG_LEVEL
      - LDAP_AUTH_METHOD
      - LDAP_BASE
      - LDAP_BINDDN
      - LDAP_BINDPW
      - LDAP_FILTER
      - LDAP_VERSION
      - LDAP_TLS_CIPHERS
      - LDAP_TLS_CHECK_PEER
      - LDAP_TLS_CACERT_FILE
      - LDAP_TLS_CACERT_DIR
      - LDAP_START_TLS
      - LDAP_URL
      - LDAP_USE_TLS
      - PUBLIC_URL
      - TURN_CREDENTIALS
      - TURN_HOST
      - TURNS_HOST
      - TURN_PORT
      - TURNS_PORT
      - TZ
      - XMPP_DOMAIN
      - XMPP_AUTH_DOMAIN
      - XMPP_GUEST_DOMAIN
      - XMPP_MUC_DOMAIN
      - XMPP_INTERNAL_MUC_DOMAIN
      - XMPP_MODULES
      - XMPP_MUC_MODULES
      - XMPP_INTERNAL_MUC_MODULES
      - XMPP_RECORDER_DOMAIN
      - XMPP_CROSS_DOMAIN
    networks:
      meet.jitsi:
        aliases:
          - ${XMPP_SERVER}
```
