### ISSUE TITLE
Multiple JVB-containers on different hosts result in video quality impairment warning

### ISSUE THREAD

**Issue by danielchristianschroeter** [jitsi/docker-jitsi-meet#1587]
I attempted to integrate an additional JVB (Jitsi Video Bridge) container into my existing Docker-based Jitsi Meet installation on a separate host. However, upon the activation of the second JVB host and subsequent creation of multiple rooms with multiple participants, a warning message emerged for participants: "Video quality impaired - The bridge channel has been disconnected and thus video quality is limited to its lowest setting.". The Jitsi conversation remains active (in reduced quality).

On the first host, within the web container, the following error logs are visible:

```
11.22.33.44 - - [21/Aug/2023:11:20:21 +0200] "GET /colibri-ws//211b0278228dd00d/d181c791?pwd=5uq0s96tun42pqfg5k43oasrgt HTTP/1.1" 502 564 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
2023/08/21 11:20:24 [error] 282#282: *43 211b0278228dd00d could not be resolved (3: Host not found), client: 11.22.33.44, server: _, request: "GET /colibri-ws//211b0278228dd00d/d181c791?pwd=5uq0s96tun42pqfg5k43oasrgt HTTP/1.1", host: "meet-test.domain.com"
```
211b0278228dd00d seems to be the confId created by the 2nd jvb instance.

In the browser console, users observe the following output:
```
BridgeChannel.js:91 WebSocket connection to 'wss://meet-test.domain.com/colibri-ws//211b0278228dd00d/d181c791?pwd=62b7c7pbe8pbc344c2gtmcl00p' failed: 
_initWebSocket @ BridgeChannel.js:91
Logger.js:154 2023-08-21T10:13:55.912Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed: 1006 
```

Here my configuration for both hosts (running with version stable-8719):
**HOST-1:**
.env
```
AUTH_TYPE=ldap
COLIBRI_REST_ENABLED=true
CONFIG=/opt/.jitsi-meet-cfg
ENABLE_AUTH=1
ENABLE_COLIBRI_WEBSOCKET=1
ENABLE_END_CONFERENCE=false
ENABLE_GUESTS=1
ENABLE_HTTP_REDIRECT=1
HTTPS_PORT=443
HTTP_PORT=80
JIBRI_RECORDER_PASSWORD=abc
JIBRI_XMPP_PASSWORD=def
JICOFO_AUTH_PASSWORD=ghi
JIGASI_XMPP_PASSWORD=jkl
JVB_AUTH_PASSWORD=mno
LDAP_AUTH_METHOD=bind
LDAP_BASE=dc=domain,dc=de
LDAP_BINDDN=jitsi-srv@domain.com
LDAP_BINDPW=XXX
LDAP_FILTER=(&(objectCategory=Person)(sAMAccountName=%u))
LDAP_TLS_CACERT_FILE=/etc/ssl/certs/ca-certificates.crt
LDAP_TLS_CHECK_PEER=1
LDAP_URL=ldaps://ldap.domain.com:636
LDAP_USE_TLS=1
LDAP_VERSION=3
PUBLIC_URL=https://meet-test.domain.com
RESTART_POLICY=unless-stopped
TZ=Europe/Berlin
JVB_ADVERTISE_IPS=<public ip host-1>
```

docker-compose.override.yml
```
version: '3.5'

services:
    # Frontend
    web:
        image: docker.domain.com/jitsi/web:stable-8719
        volumes:
            - /opt/ssl/star.domain.com.pem:/config/keys/cert.crt:Z
            - /opt/ssl/star.domain.com.key:/config/keys/cert.key:Z
            - /opt/jitsi_watermark.png:/usr/share/jitsi-meet/images/watermark.png
            - /opt/custom-config.js:/config/custom-config.js
            - /opt/custom-interface_config.js:/config/custom-interface_config.js
    # XMPP server
    prosody:
        image: docker.domain.com/jitsi/prosody:stable-8719
        ports:
          - '5222:5222'
    # Conference focus component
    jicofo:
        image: docker.domain.com/jitsi/jicofo:stable-8719
    # Video router/bridge
    jvb:
        hostname: jvb1
        image: docker.domain.com/jitsi/jvb:stable-8719
        expose:
          - '4096/udp' # required for OCTO
```

**HOST-2:**
.env
```
AUTH_TYPE=ldap
COLIBRI_REST_ENABLED=true
CONFIG=/opt/.jitsi-meet-cfg
ENABLE_AUTH=1
ENABLE_COLIBRI_WEBSOCKET=1
ENABLE_END_CONFERENCE=false
ENABLE_GUESTS=1
ENABLE_HTTP_REDIRECT=1
HTTPS_PORT=443
HTTP_PORT=80
JIBRI_RECORDER_PASSWORD=<same as host-1>
JIBRI_XMPP_PASSWORD=<same as host-1>
JICOFO_AUTH_PASSWORD=<same as host-1>
JIGASI_XMPP_PASSWORD=<same as host-1>
JVB_AUTH_PASSWORD=<same as host-1>
LDAP_AUTH_METHOD=bind
LDAP_BASE=dc=domain,dc=de
LDAP_BINDDN=jitsi-srv@domain.com
LDAP_BINDPW=XXX
LDAP_FILTER=(&(objectCategory=Person)(sAMAccountName=%u))
LDAP_TLS_CACERT_FILE=/etc/ssl/certs/ca-certificates.crt
LDAP_TLS_CHECK_PEER=1
LDAP_URL=ldaps://ldap.domain.com:636
LDAP_USE_TLS=1
LDAP_VERSION=3
PUBLIC_URL=https://meet-test.domain.com
RESTART_POLICY=unless-stopped
TZ=Europe/Berlin
XMPP_SERVER=<public ip host-1>
JVB_ADVERTISE_IPS=<public ip host-2>
```

docker-compose.yml
```
version: '3.5'

services:
    # Video router/bridge
    jvb:
        hostname: jvb2
        image: docker.domain.com/jitsi/jvb:stable-8719
        restart: unless-stopped
        expose:
            - '4096/udp' # required for OCTO
        ports:
            - '10000:10000/udp'
            - '127.0.0.1:8080:8080'
        volumes:
            - /opt/.jitsi-meet-cfg/jvb:/config:Z
        environment:
            - DOCKER_HOST_ADDRESS
            - ENABLE_COLIBRI_WEBSOCKET
            - ENABLE_JVB_XMPP_SERVER
            - ENABLE_OCTO
            - JVB_ADVERTISE_IPS
            - JVB_ADVERTISE_PRIVATE_CANDIDATES
            - JVB_AUTH_USER
            - JVB_AUTH_PASSWORD
            - JVB_BREWERY_MUC
            - JVB_DISABLE_STUN
            - JVB_PORT
            - JVB_MUC_NICKNAME
            - JVB_STUN_SERVERS
            - JVB_OCTO_BIND_ADDRESS
            - JVB_OCTO_REGION
            - JVB_OCTO_RELAY_ID
            - JVB_WS_DOMAIN
            - JVB_WS_SERVER_ID
            - JVB_XMPP_AUTH_DOMAIN
            - JVB_XMPP_INTERNAL_MUC_DOMAIN
            - JVB_XMPP_PORT
            - JVB_XMPP_SERVER
            - PUBLIC_URL
            - SENTRY_DSN=0
            - SENTRY_ENVIRONMENT
            - SENTRY_RELEASE
            - COLIBRI_REST_ENABLED
            - SHUTDOWN_REST_ENABLED
            - TZ
            - XMPP_AUTH_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_SERVER
            - XMPP_PORT
        networks:
            meet.jitsi:

networks:
    meet.jitsi:

```

Does anyone have experience for additional JVBs on additional hosts?
