### ISSUE TITLE
Deploying Jitsi in Kubernetes as DIND

### ISSUE THREAD

**Issue by kevinmnm** [jitsi/docker-jitsi-meet#1596]
# Description:

I'm trying to deploy Jitsi in Kubernetes cluster and I'm unable to make it work properly. I first tried to use [Kompose](https://kompose.io/) but that didn't work. So I decided to simply run [Jitsi's docker-compose deployment](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker/) inside of a single Docker instance ([Docker-in-Docker](https://hub.docker.com/_/docker)) to make things simpler. I'm currently using [Jitsi version 8719](https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-8719) but would also like to use newer version if needed. I'm specifically using [K3S](https://k3s.io/) for Kubernetes cluster (I doubt this will matter).

# Steps to reproduce:

1. Extract files from [release](https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-8719).
2. Add `privileged: true` under each services in [**docker-compose.yml**](https://github.com/jitsi/docker-jitsi-meet/blob/master/docker-compose.yml).
3. Add custom Dockerfile to deploy as [DIND](https://hub.docker.com/_/docker). **This is my current Dockerfile:**
```Dockerfile
### This will follow https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker/

FROM docker:23.0.6-dind-alpine3.18

RUN apk add --no-cache bash

RUN mkdir -p \
   ~/.jitsi-meet-cfg/web \
   ~/.jitsi-meet-cfg/transcripts \
   ~/.jitsi-meet-cfg/prosody/config \
   ~/.jitsi-meet-cfg/prosody/prosody-plugins-custom \
   ~/.jitsi-meet-cfg/jicofo \
   ~/.jitsi-meet-cfg/jvb \
   ~/.jitsi-meet-cfg/jigasi \
   ~/.jitsi-meet-cfg/jibri

WORKDIR /app/

COPY . .

RUN rm -f .env
RUN cp env.example .env

RUN chmod +x gen-passwords.sh
RUN sed -i -e 's/\r$//' gen-passwords.sh
RUN ./gen-passwords.sh


RUN chmod +x docker-entrypoint.sh
RUN sed -i -e 's/\r$//' docker-entrypoint.sh

ENTRYPOINT ["./docker-entrypoint.sh"]

EXPOSE 8000 8443
```
4. Add K8 resources. **This is my current manifests:**
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jitsi-dep
  namespace: jitsi-system
spec:
  selector:
    matchLabels:
      app: jitsi-pod
  template:
    metadata:
      labels:
        app: jitsi-pod
    spec:
      # hostNetwork: true
      # hostPID: true
      # hostIPC: true
      containers:
        - name: jitsi-cont
          image: <custom built Jitsi Dockerfile registry>
          imagePullPolicy: "Always"
          securityContext:
            privileged: true
          resources: {}
          ports:
            - containerPort: 8000
      volumes:
        - name: jitsi-volume
          persistentVolumeClaim:
            claimName: jitsi-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jitsi-svc
  namespace: jitsi-system
spec:
  type: "ClusterIP"
  selector:
    app: jitsi-pod
  ports:
    - port: 8000
      targetPort: 8000
      name: jitsi-svc-port
    - port: 8443
      targetPort: 8443
      name: jitsi-svc-https-port
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jitsi-pvc
  namespace: jitsi-system
spec:
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 2Gi
  volumeMode: "Filesystem"
  accessModes:
    - ReadWriteMany
---

```

# Expected behavior:

Fully working Jitsi in Kubernetes cluster.

# Actual behavior:

As soon as I "Start meeting", I get this popup:
![image](https://github.com/jitsi/jitsi-meet/assets/62520825/c14faeca-6ddc-4bf9-8115-ffd6e2b0ea49)
I'm assuming it's  related to Websockets.

# Server information:

- Jitsi Meet version: [8719](https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-8719)
- Operating System: Ubuntu 22.04 but deploying in Kubernetes cluster ([K3S](https://k3s.io/))

# Client information:

- Browser / app version: Chromium and others
- Operating System: Development is done in Windows 11
