### ISSUE TITLE
Adding a `custom-interface_config.js` file breaks welcome page settings

### ISSUE THREAD

**Issue by BinaryWizard904** [jitsi/docker-jitsi-meet#1786]
I need to add a `custom-interface_config.js` file to add an additional welcomePageCard that explains how to set an avatar.  Currently I am doing so by editing the docker-compose file to include the `custom-interface_config.js` file alongside other required files as a config files.

This works, insofar as the Welcome Page Card is displayed with appropriate content.  However, if you click the "settings" gear button, the entire screen goes black, the title changes to "undefined", and the console displays the error: 
`2024-04-22T16:55:46.134Z [features/base/app] <componentDidCatch>:  TypeError: interfaceConfig.SETTINGS_SECTIONS is undefined`.

Not sure if this is a bug or if I just got the syntax wrong.  The handbook [doesn't say](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker#jitsi-meet-configuration) what the syntax of custom config or interface_config files is.  But it does say that "It's enough to provide your relevant settings only, the docker scripts will append your custom files to the default ones!" 

### Here is my tiny `custom-interface_config.js` file:
```
var interfaceConfig = {
	DISPLAY_WELCOME_PAGE_ADDITIONAL_CARD: true
}
```

### I made the following changes to the docker-compose.yml
```
version: '3.5'

configs:
    # Web GUI Customizations
    avatar_instructions_img:
        file: ../assets/AvatarInstructions.png
    welcome_page_card:
        file: ../assets/welcomePageAdditionalCard.html
    custom_interface_config:
        file: ../conf/web/custom-interface_config.js
services:
    # Frontend
    web:
        image: docker.io/jitsi/web:${JITSI_IMAGE_VERSION:-stable-9364-1}
        configs:
            # Custom Welcome Page
            - source: avatar_instructions_img
              target: /usr/share/jitsi-meet/images/AvatarInstructions.png
            - source: welcome_page_card
              target: /usr/share/jitsi-meet/static/welcomePageAdditionalCard.html
            - source: custom_interface_config
              target: /config/custom-interface_config.js
...
```
