### ISSUE TITLE
Docker swarm support

### ISSUE THREAD

**Issue by johackim** [jitsi/docker-jitsi-meet#1800]
This stack works with `docker-compose up` but not with `docker stack deploy -c docker-compose.yml jitsi` (Docker Swarm):

```yml
version: '3.8'

x-defaults: &defaults
  environment:
    - TZ=Europe/Paris
    - PUBLIC_URL=https://jitsi.example.com
    - ENABLE_LETSENCRYPT=1
    - ENABLE_HTTP_REDIRECT=1
    - LETSENCRYPT_DOMAIN=jitsi.example.com
    - LETSENCRYPT_EMAIL=noreply@example.com
    - JICOFO_AUTH_PASSWORD=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    - JVB_AUTH_PASSWORD=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    - JIGASI_XMPP_PASSWORD=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    - JIBRI_RECORDER_PASSWORD=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    - JIBRI_XMPP_PASSWORD=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

services:
  web:
    <<: *defaults
    image: jitsi/web:${JITSI_IMAGE_VERSION:-unstable}
    ports:
      - '80:80'
      - '443:443'
    networks:
      internal:

  prosody:
    <<: *defaults
    image: jitsi/prosody:${JITSI_IMAGE_VERSION:-unstable}
    networks:
      internal:
        aliases:
          - ${XMPP_SERVER:-xmpp.meet.jitsi}

  jicofo:
    <<: *defaults
    image: jitsi/jicofo:${JITSI_IMAGE_VERSION:-unstable}
    networks:
      internal:

  jvb:
    <<: *defaults
    image: jitsi/jvb:${JITSI_IMAGE_VERSION:-unstable}
    ports:
      - target: ${JVB_UDP_PORT:-10000}
        published: ${JVB_UDP_PORT:-10000}
        protocol: udp
        mode: host
    networks:
      internal:

networks:
  internal:
    driver: overlay
    attachable: true
```

Steps to reproduce:

- `docker stack deploy -c docker-compose.yml jitsi`
- Create a room with 2 participants

The video doesn't work between the participants.

And it works perfectly with `docker-compose`.

Thanks for your help!
