### ISSUE TITLE
firewalld breaks jitsi-docker

### ISSUE THREAD

**Issue by ffallah** [jitsi/docker-jitsi-meet#1889]
I have a self hosted Jitsi docker running on a VPS, It was working fine until I installed firewalld. I have opened all the required ports for Jitsi :
```
#firewall-cmd --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth0
  sources:
  services: cockpit dhcpv6-client http https ssh
  ports: 8443/tcp 10000/udp 4443/tcp 5222/tcp 5349/tcp 5280/tcp 80/tcp 443/tcp
  protocols:
  forward: yes
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
```
but I get this error in console log :
```
WebSocket connection to 'wss://xxxxx/xmpp-websocket?room=xxxxx' failed
```
If I stop firewalld, then it starts working again.
somehow firewalld is interfereing with Jitsi.
Does anyone has any clues ?
