### ISSUE TITLE
Running my own docker-compose file with nginx fails (JitsiMeetJS is not defined)

### ISSUE THREAD

**Issue by PeterGDSoft** [jitsi/docker-jitsi-meet#1898]
Hi, I have such an app to create docker configuration and automatic deployment, I wanted to fire jitsi using docker compose, I wanted such the simplest version of jitsi enabled behind nginx.

I understand that this part is unnecessary if I download the most necessary things from the docker repository?

wget $(curl -s https://api.github.com/repos/jitsi/docker-jitsi-meet/releases/latest | grep 'zip' | cut -d” -f4)

also i don't really understand why we create config directories?, they won't create themselves since they are docker volumes?

mkdir -p ~/.jitsi-meet-cfg/{web,transcripts,prosody/config,prosody/prosody-plugins-custom,jicofo,jvb,jigasi,jibri}

The problem is that when I go to the configured jitsi address I get an error:

![image](https://github.com/user-attachments/assets/75a1cc25-7fce-4a1e-8695-88b025032a96)

Here is my config for jitsi (everything works in one container):

```yml
version: "3.8"
services:
  jitsi-jicofo:
    container_name: jitsi-jicofo_d4
    image: jitsi/jicofo:stable-9646
    environment:
      AUTH_TYPE: "jwt"
      ENABLE_AUTH: "1"
      ENABLE_AUTO_LOGIN: "1"
      JICOFO_AUTH_PASSWORD: "jicofo_pass"
      JICOFO_AUTH_USER: "focus"
      XMPP_SERVER: "jitsi-prosody"
    volumes:
      - ./.jitsi-meet-cfg/jicofo:/config:Z
  jitsi-jvb:
    container_name: jitsi-jvb_d4
    image: jitsi/jvb:stable-9646
    ports:
      - "10000:10000/udp"
    environment:
      JVB_ADVERTISE_IPS: "192.168.1.1"
      JVB_AUTH_PASSWORD: "jvb_pass"
      XMPP_SERVER: "jitsi-prosody"
    volumes:
      - ./.jitsi-meet-cfg/jvb:/config:Z
  jitsi-prosody:
    container_name: jitsi-prosody_d4
    image: jitsi/prosody:stable-9646
    environment:
      AUTH_TYPE: "jwt"
      ENABLE_AUTH: "1"
      ENABLE_GUESTS: "0"
      JICOFO_AUTH_PASSWORD: "jicofo_pass"
      JVB_AUTH_PASSWORD: "jvb_pass"
      JWT_APP_ID: "issuer"
      JWT_APP_SECRET: "jwt_secret"
      JWT_AUTH_TYPE: "token"
      JWT_TOKEN_AUTH_MODULE: "token_verifictation"
    volumes:
      - ./.jitsi-meet-cfg/prosody:/config:Z
      - ./.jitsi-meet-cfg/prosody-plugins-custom:/prosody-plugins-custom:Z
  jitsi-web:
    container_name: jitsi-web_d4
    image: jitsi/web:stable-9646
    environment:
      DISABLE_HTTPS: "1"
      ENABLE_AUTH: "1"
      ENABLE_GUESTS: "0"
      ENABLE_HTTP_REDIRECT: "0"
      ENABLE_LETSENCRYPT: "0"
      PUBLIC_URL: "my_url"
      XMPP_SERVER: "jitsi-prosody"
    volumes:
      - ./.jitsi-meet-cfg/web:/config:Z
      - ./.jitsi-meet-cfg/web/crontabs:/var/spool/cron/crontabs:Z
      - ./.jitsi-meet-cfg/web/transcripts:/usr/share/jitsi-meet/transcripts:Z
```
