### ISSUE TITLE
Make usable behind reverse proxy (like https://meet.jit.si/)

### ISSUE THREAD

**Issue by nicolaspernoud** [jitsi/docker-jitsi-meet#22]
https://meet.jit.si/ is usable behind a corporate reverse proxy (only TCP ports 80 and 443 allowed).
It would be amazing if the self hosted dockerised version would be as well...

Thanks.

Best regards and kudos for the fantastic work...

**Comment by saghul** [comment]
@damencho We could also use that nginx module to proxy to a different upstream based on ALPN, right? That would be to do TURN on 443.

**Comment by damencho** [comment]
Maybe, we need to test it, whether it works :)

**Comment by damencho** [comment]
Nope, there is nothing we had tried, here is some stuff that I was reading:
https://superuser.com/questions/1135208/can-nginx-serve-ssh-and-https-at-the-same-time-on-the-same-port
http://nginx.org/en/docs/stream/ngx_stream_ssl_preread_module.html#ssl_preread
The idea is nginx to detect https web traffic and serve the web (or bosh), but the rest to be considered as media traffic and forwarded to coturn tcp port, or the other way around, detect coturn traffic and forward it and the rest consider to be served by nginx. This way we can use port 443 for both serving the web and media.

**Comment by alexcustos** [comment]
It seems I ran into the same issue. It's described well here https://github.com/jitsi/jitsi-meet/issues/2805. I tried to use Turncredentials module to point my Coturn server, but Prosody crashes immediately after login, even with this module disabled. It's enough to have it in modules path.

So I would like to know if there is any way to enable TURN server for this Docker Compose setup?

<details>
<summary>Here's the relevant part of the log file</summary>

```
jitsi_prosody | mod_bosh                                  info  New BOSH session, assigned it sid 'c9307ab7-ad92-4493-992c-32cc6443b207'
jitsi_prosody | boshc9307ab7-ad92-4493-992c-32cc6443b207  info  Authenticated as hcisowftdjhb22or@guest.meet.jitsi
jitsi_prosody | mod_bosh                                  error Traceback[bosh]: /usr/lib/prosody/util/stanza.lua:62: invalid attribute value: expected string, got number
jitsi_prosody | stack traceback:
jitsi_prosody |         [C]: in function 'error'
jitsi_prosody |         /usr/lib/prosody/util/stanza.lua:62: in function 'check_text'
jitsi_prosody |         /usr/lib/prosody/util/stanza.lua:75: in function 'check_attr'
jitsi_prosody |         /usr/lib/prosody/util/stanza.lua:87: in function 'new_stanza'
jitsi_prosody |         /usr/lib/prosody/util/stanza.lua:109: in function 'tag'
jitsi_prosody |         /modules/mod_turncredentials.lua:28: in function '?'
jitsi_prosody |         /usr/lib/prosody/util/events.lua:79: in function </usr/lib/prosody/util/events.lua:75>
jitsi_prosody |         (...tail calls...)
jitsi_prosody |         /usr/lib/prosody/util/events.lua:79: in function </usr/lib/prosody/util/events.lua:75>
jitsi_prosody |         (...tail calls...)
jitsi_prosody |         /usr/lib/prosody/core/stanza_router.lua:180: in function 'core_post_stanza'
jitsi_prosody |         /usr/lib/prosody/core/stanza_router.lua:127: in function 'dispatch_stanza'
jitsi_prosody |         /usr/lib/prosody/modules/mod_bosh.lua:305: in function 'func'
jitsi_prosody |         /usr/lib/prosody/util/async.lua:127: in function </usr/lib/prosody/util/async.lua:125>
jitsi_prosody | stack traceback:
jitsi_prosody |         /usr/lib/prosody/util/async.lua:211: in function 'run'
jitsi_prosody |         /usr/lib/prosody/modules/mod_bosh.lua:447: in function 'cb_handlestanza'
jitsi_prosody |         /usr/lib/prosody/util/xmppstream.lua:182: in function </usr/lib/prosody/util/xmppstream.lua:162>
jitsi_prosody |         [C]: in function 'parse'
jitsi_prosody |         /usr/lib/prosody/util/xmppstream.lua:282: in function 'feed'
jitsi_prosody |         /usr/lib/prosody/modules/mod_bosh.lua:133: in function '?'
jitsi_prosody |         /usr/lib/prosody/util/events.lua:79: in function </usr/lib/prosody/util/events.lua:75>
jitsi_prosody |         (...tail calls...)
jitsi_prosody |         /usr/lib/prosody/net/http/server.lua:228: in function </usr/lib/prosody/net/http/server.lua:176>
jitsi_prosody |         [C]: in function 'xpcall'
jitsi_prosody |         /usr/lib/prosody/net/http/server.lua:108: in function 'process_next'
jitsi_prosody |         /usr/lib/prosody/net/http/server.lua:124: in function 'success_cb'
jitsi_prosody |         /usr/lib/prosody/net/http/parser.lua:177: in function 'feed'
jitsi_prosody |         /usr/lib/prosody/net/http/server.lua:155: in function </usr/lib/prosody/net/http/server.lua:154>
jitsi_prosody |         (...tail calls...)
jitsi_prosody |         /usr/lib/prosody/net/server_select.lua:915: in function </usr/lib/prosody/net/server_select.lua:899>
jitsi_prosody |         [C]: in function 'xpcall'
jitsi_prosody |         /usr/bin/prosody:80: in function 'loop'
jitsi_prosody |         /usr/bin/prosody:90: in main chunk
jitsi_prosody |         [C]: in ?
jitsi_prosody | boshc9307ab7-ad92-4493-992c-32cc6443b207  info  BOSH client disconnected: session close
```
</details>

**Comment by saghul** [comment]
> So I would like to know if there is any way to enable TURN server for this Docker Compose setup?

Not at the moment, sorry.

**Comment by madmath03** [comment]
It seems I have managed to fix this with #147, but that seemed far simpler than what I expected when reading earlier exchange regarding NGinx.

My P2P connections are using our dockerized Coturn server behind a reverse proxy, and I can successfully see Coturn receiving connections and am able to call other people on different networks.

In terms of configuration, I'm using something similar to this:
```yml

  # Frontend
  web:
    #image: jitsi/web
    image: monogramm/jitsi-web:dev
    # ...
    environment:
      - JVB_ENABLE_STUN_TURN=1
      - JVB_ENABLE_P2P_STUN_TURN=1
      # ...

  # XMPP server
  prosody:
    #image: jitsi/prosody
    image: monogramm/jitsi-prosody:dev
    # ...
    environment:
      - GLOBAL_MODULES=turncredentials
      - GLOBAL_CONFIG=turncredentials_secret = "${COTURN_TURN_SECRET}";\nturncredentials_host = "turn.${DOMAIN}";\nturncredentials_port = 5349;
      # ...

  # Coturn
  coturn:
    image: monogramm/docker-coturn:4
    container_name: coturn
    restart: always
    network_mode: "host"
    tty: true
    expose:
      - '3478'
      - '5349'
      - '3479'
      - '5350'
    environment:
      - LISTENING_PORT=3478
      - TLS_LISTENING_PORT=5349
      - ALT_LISTENING_PORT=3479
      - ALT_TLS_LISTENING_PORT=5350
      - LISTEN_IPS=${COTURN_LISTEN_IPS}
      - RELAY_IP=${COTURN_RELAY_IP}
      - STATIC_AUTH_SECRET=${COTURN_TURN_SECRET}
      - TLS_CERT=/ssl/coturn/live/${DOMAIN}/fullchain.pem
      - TLS_KEY=/ssl/coturn/live/${DOMAIN}/privkey.pem
      - REALM=turn.${DOMAIN}
      - VERBOSE=1
      - DEBUG=0
      - PROD=1
    volumes:
      - /srv/coturn/data:/srv
      - /etc/letsencrypt/live/${DOMAIN}:/ssl/coturn/live/${DOMAIN}:ro
      - /etc/letsencrypt/archive/${DOMAIN}:/ssl/coturn/archive/${DOMAIN}:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
```

What do you guys think ?
