### ISSUE TITLE
Traefik Deployment questions

### ISSUE THREAD

**Issue by Dextroz** [jitsi/docker-jitsi-meet#220]
Hello 😃 

I am looking into deploying Jitsi using Traefik. I am looking for basic audio and video call functionality.

For this, do I need to deploy `jigasi` ?

Furthermore:
1. If using Traefik, do I need to uncomment the `PUBLIC_URL` environment variable?
2. I don't require any recording/streaming of calls/video etc, how do I ensure this is disabled?

I assume I will need to ensure the relevant ports are open and forwarded correctly too.

Thanks in advance :-)

**Comment by jakesmolka** [comment]
Hey! I don't know if you got your setup running and just what to get more into it - or you seek help getting your setup running. If it is the latter, I can give you my jitsi + traefik setup as example how it works for me.

From the perspective of my experience and not being an expert, regarding your questions: 
- I don't run `jigasi`. In fact, I didn't know what it was until now, because I just used the basic [docker-compose file](https://github.com/jitsi/docker-jitsi-meet/blob/master/docker-compose.yml) provided here.
- I uncommented and added my value to the `PUBLIC_URL` in the `.env` file. But I'm not sure if it really is necessary.
- I would say, make sure `ENABLE_RECORDING` stays commented (i.e. not set to `1`) and you don't accidentally deploy `jibri`. Again, this is not the case if you only the the basic docker-compose file.

**Comment by Dextroz** [comment]
Hi @jakesmolka,

Thanks for replying. Would you able to share your example please? 

Thanks.

**Comment by saghul** [comment]
We have an examples directory in the dev branch, you are welcome to contribute your config with a PR so we can add it there!

**Comment by SebastianKobs** [comment]
Hi, working example(at least for me) with traefik.


- Remove the port-bindings for the web service. 
- Add your external network (e.g. web) in the network-sections 
- Add your labels.  

I've added comments to the relevant parts, otherwise it's the default.
Make sure to uncomment and add your host ip in .env : 
````
DOCKER_HOST_ADDRESS=1.2.3.4
````
Example docker-compose.yml with traefik(still running on traefik 1.7). 
````
version: '3'

services:
    # Frontend
    web:
        image: jitsi/web
        #traefik
        #ports:
        #    - '${HTTP_PORT}:80'
        #    - '${HTTPS_PORT}:443'
        #traefik end
        volumes:
            - ${CONFIG}/web:/config
            - ${CONFIG}/web/letsencrypt:/etc/letsencrypt
            - ${CONFIG}/transcripts:/usr/share/jitsi-meet/transcripts
        environment:
            - ENABLE_AUTH
            - ENABLE_GUESTS
            - ENABLE_LETSENCRYPT
            - ENABLE_HTTP_REDIRECT
            - ENABLE_TRANSCRIPTIONS
            - DISABLE_HTTPS
            - JICOFO_AUTH_USER
            - LETSENCRYPT_DOMAIN
            - LETSENCRYPT_EMAIL
            - PUBLIC_URL
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_BOSH_URL_BASE
            - XMPP_GUEST_DOMAIN
            - XMPP_MUC_DOMAIN
            - XMPP_RECORDER_DOMAIN
            - ETHERPAD_URL_BASE
            - TZ
            - JIBRI_BREWERY_MUC
            - JIBRI_PENDING_TIMEOUT
            - JIBRI_XMPP_USER
            - JIBRI_XMPP_PASSWORD
            - JIBRI_RECORDER_USER
            - JIBRI_RECORDER_PASSWORD
            - ENABLE_RECORDING
        networks:
            #traefik
            web:
            #traefik end
            meet.jitsi:
                aliases:
                    - ${XMPP_DOMAIN}
        #traefik
        labels:
            - "traefik.docker.network=web"
            - "traefik.enable=true"
            - "traefik.backend=jc_backend"
            - "traefik.basic.frontend.rule=Host:your.host.name"
            - "traefik.basic.port=80"
         #traefik end

    # XMPP server
    prosody:
        image: jitsi/prosody
        expose:
            - '5222'
            - '5347'
            - '5280'
        volumes:
            - ${CONFIG}/prosody:/config
        environment:
            - AUTH_TYPE
            - ENABLE_AUTH
            - ENABLE_GUESTS
            - GLOBAL_MODULES
            - GLOBAL_CONFIG
            - LDAP_URL
            - LDAP_BASE
            - LDAP_BINDDN
            - LDAP_BINDPW
            - LDAP_FILTER
            - LDAP_AUTH_METHOD
            - LDAP_VERSION
            - LDAP_USE_TLS
            - LDAP_TLS_CIPHERS
            - LDAP_TLS_CHECK_PEER
            - LDAP_TLS_CACERT_FILE
            - LDAP_TLS_CACERT_DIR
            - LDAP_START_TLS
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_GUEST_DOMAIN
            - XMPP_MUC_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_MODULES
            - XMPP_MUC_MODULES
            - XMPP_INTERNAL_MUC_MODULES
            - XMPP_RECORDER_DOMAIN
            - JICOFO_COMPONENT_SECRET
            - JICOFO_AUTH_USER
            - JICOFO_AUTH_PASSWORD
            - JVB_AUTH_USER
            - JVB_AUTH_PASSWORD
            - JIGASI_XMPP_USER
            - JIGASI_XMPP_PASSWORD
            - JIBRI_XMPP_USER
            - JIBRI_XMPP_PASSWORD
            - JIBRI_RECORDER_USER
            - JIBRI_RECORDER_PASSWORD
            - JWT_APP_ID
            - JWT_APP_SECRET
            - JWT_ACCEPTED_ISSUERS
            - JWT_ACCEPTED_AUDIENCES
            - JWT_ASAP_KEYSERVER
            - JWT_ALLOW_EMPTY
            - JWT_AUTH_TYPE
            - JWT_TOKEN_AUTH_MODULE
            - LOG_LEVEL
            - TZ
        networks:
            meet.jitsi:
                aliases:
                    - ${XMPP_SERVER}

    # Focus component
    jicofo:
        image: jitsi/jicofo
        volumes:
            - ${CONFIG}/jicofo:/config
        environment:
            - ENABLE_AUTH
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_SERVER
            - JICOFO_COMPONENT_SECRET
            - JICOFO_AUTH_USER
            - JICOFO_AUTH_PASSWORD
            - JICOFO_RESERVATION_REST_BASE_URL
            - JVB_BREWERY_MUC
            - JIGASI_BREWERY_MUC
            - JIBRI_BREWERY_MUC
            - JIBRI_PENDING_TIMEOUT
            - TZ
        depends_on:
            - prosody
        networks:
            meet.jitsi:

    # Video bridge
    jvb:
        image: jitsi/jvb
        ports:
            - '${JVB_PORT}:${JVB_PORT}/udp'
            - '${JVB_TCP_PORT}:${JVB_TCP_PORT}'
        volumes:
            - ${CONFIG}/jvb:/config
        environment:
            - DOCKER_HOST_ADDRESS
            - XMPP_AUTH_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_SERVER
            - JVB_AUTH_USER
            - JVB_AUTH_PASSWORD
            - JVB_BREWERY_MUC
            - JVB_PORT
            - JVB_TCP_HARVESTER_DISABLED
            - JVB_TCP_PORT
            - JVB_STUN_SERVERS
            - JVB_ENABLE_APIS
            - TZ
        depends_on:
            - prosody
        networks:
            meet.jitsi:

# Custom network so all services can communicate using a FQDN
networks:
    meet.jitsi:
    #traefik
    web:
        external: true
    #traefik end
````
