### ISSUE TITLE
got error after GCP deployment

### ISSUE THREAD

**Issue by madhura2** [jitsi/docker-jitsi-meet#286]
I followed the example/kubernetes on dev branch
performed the following commands:
kubectl apply -f jvb-udp.service.yaml
kubectl apply -f deployment.yaml
kubectl apply -f web-service.yaml

after checking this web-service.yaml in the jitsi-ingress
I got the following error:

**error while evaluating the ingress spec: service "jitsi/web" is type "ClusterIP", expected "NodePort" or "LoadBalancer"**

The ingress is expecting this web-service.yaml to be NodePort,
So how to do that...any one?
and after exposing it as NodePort it is still not working

what should be done?

**Comment by iGoogledYouYesterday** [comment]
I had the same issue yesterday. 

In my case the issue was that i already had Nginx Ingress set up on my cluster - so I had to add the annotations for Nginx to my Ingress class 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {DEPLOYMENT_NAME}
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
```

One more thing to notice - if you have a ingress controller in default namespace, you will have to delete namespaces from all of the files here - that solved the problems that I had.
