### ISSUE TITLE
Docker Performance

### ISSUE THREAD

**Issue by PrinzMonty** [jitsi/docker-jitsi-meet#345]
When is set kernel settings with sysctl in composer file (for testing):

```       
    # Video bridge
    jvb:
        image: jitsi/jvb
        sysctls:
            net.core.rmem_max: 2097152
            net.core.wmem_max: 2097152
            net.ipv4.tcp_rmem: 4096 87380 2097152
            net.ipv4.tcp_wmem: 4096 65536 2097152
        ports:
            - '${JVB_PORT}:${JVB_PORT}/udp'
            - '${JVB_TCP_PORT}:${JVB_TCP_PORT}'
        volumes:

```
i becomes this error:

```
ERROR: for dockerjitsimeet_jvb_1  Cannot start service jvb: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"write sysctl key net.ipv4.tcp_wmem: open /proc/sys/net/ipv4/tcp_wmem: no such file or directory\"": unknown
```

Is this a docker problem?

Settings are from here:

https://community.jitsi.org/t/high-e2e-rtt-value-and-low-quality/24175/8
