### ISSUE TITLE
You have been disconnected

### ISSUE THREAD

**Issue by BolkoSchreiber** [jitsi/docker-jitsi-meet#405]
Hi since the last version, I cannot get it running anymore. 
When trying to join a channel, I get the "You have been disconnected" error.

cosole output:

```
2020-04-07T19:58:16.183Z [features/base/tracks] <E/</<>:  Failed to create local tracks 
Array [ "audio", "video" ]
 
Object { gum: {…}, name: "gum.not_found", message: "Requested device(s) was/were not found: audio, video", stack: "a@https://jitsi.mydomain.de/libs/lib-jitsi-meet.min.js?v=3969:1:120043\nvalue/</<@https://jitsi.mydomain.de/libs/lib-jitsi-meet.min.js?v=3969:1:98340\n" }
Logger.js:154:22
2020-04-07T19:58:16.195Z [modules/RTC/RTCUtils.js] <value>:  Using the new gUM flow Logger.js:154:22
2020-04-07T19:58:16.195Z [modules/RTC/RTCUtils.js] <value/i<>:  Got media constraints:  
Object { video: false, audio: {…} }
Logger.js:154:22
2020-04-07T19:58:16.290Z [JitsiMeetJS.js] <getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  Error: "Strophe: request id 1.1 error 404 happened"
    log strophe.util.js:89
    error strophe.umd.js:1392
    _onRequestStateChange strophe.umd.js:5017
```

I have not activated the lets encrypt option in jitsi - i have an external nginx reverse proxy + lets encrypt solution in place, because there are some more webservices running on my server.

my .env file:

```
# Security
#
# Set these to strong passwords to avoid intruders from impersonating a service account
# The service(s) won't start unless these are specified
# Running ./gen-passwords.sh will update .env with strong passwords
# You may skip the Jigasi and Jibri passwords if you are not using those
# DO NOT reuse passwords
#

# XMPP component password for Jicofo
JICOFO_COMPONENT_SECRET=780af82eeece052887e42ec38a1dd9ec

# XMPP password for Jicofo client connections
JICOFO_AUTH_PASSWORD=9e04d6a4aaf56ba5b290f40c393992e0

# XMPP password for JVB client connections
JVB_AUTH_PASSWORD=9a71f2d3aea4904ec5508478f43cc1a7

# XMPP password for Jigasi MUC client connections
JIGASI_XMPP_PASSWORD=2326c2b4ea64421c0e9742791cfbd1e4

# XMPP recorder password for Jibri client connections
JIBRI_RECORDER_PASSWORD=d904863a72cd9b2359078952fdc20319

# XMPP password for Jibri client connections
JIBRI_XMPP_PASSWORD=50eb068f54e587d20d3d792611cb8564


#
# Basic configuration options
#

# Directory where all configuration will be stored
CONFIG=/data/jitsi

# Exposed HTTP port
HTTP_PORT=80

# Exposed HTTPS port
HTTPS_PORT=443

# System time zone
TZ=Europe/Berlin

# Public URL for the web service
PUBLIC_URL="https://jitsi.mydomain.de"

# IP address of the Docker host
# See the "Running behind NAT or on a LAN environment" section in the README
#DOCKER_HOST_ADDRESS=192.168.1.1


#
# Let's Encrypt configuration
#

# Enable Let's Encrypt certificate generation
#ENABLE_LETSENCRYPT=1
[...]
# Disable HTTPS: handle TLS connections outside of this setup
DISABLE_HTTPS=1

# Redirect HTTP traffic to HTTPS
# Necessary for Let's Encrypt, relies on standard HTTPS port (443)
#ENABLE_HTTP_REDIRECT=1
```
my docker-compose.yml:

```
version: '3'

services:
  # Frontend
  web:
    image: jitsi/web
    container_name: jitsi-web
# removed exposed ports - entrypoint is my reverse proxy
    volumes:
      - ${CONFIG}/web:/config
      - ${CONFIG}/web/letsencrypt:/etc/letsencrypt
      - ${CONFIG}/transcripts:/usr/share/jitsi-meet/transcripts
    environment:
      - ENABLE_AUTH
      - ENABLE_GUESTS
      - ENABLE_LETSENCRYPT
      - ENABLE_HTTP_REDIRECT
      - ENABLE_TRANSCRIPTIONS
      - DISABLE_HTTPS
      - JICOFO_AUTH_USER
      - LETSENCRYPT_DOMAIN
      - LETSENCRYPT_EMAIL
      - PUBLIC_URL
      - XMPP_DOMAIN
      - XMPP_AUTH_DOMAIN
      - XMPP_BOSH_URL_BASE
      - XMPP_GUEST_DOMAIN
      - XMPP_MUC_DOMAIN
      - XMPP_RECORDER_DOMAIN
      - ETHERPAD_URL_BASE
      - TZ
      - JIBRI_BREWERY_MUC
      - JIBRI_PENDING_TIMEOUT
      - JIBRI_XMPP_USER
      - JIBRI_XMPP_PASSWORD
      - JIBRI_RECORDER_USER
      - JIBRI_RECORDER_PASSWORD
      - ENABLE_RECORDING
      # reverse proxy & lets encrypt companion:
      - VIRTUAL_HOST=jitsi.mydomain.de
      - LETSENCRYPT_HOST=jitsi.mydomain.de
      - LETSENCRYPT_EMAIL=me@mydomain.de
    networks:
      nextcloud_network:
        aliases:
          - ${XMPP_DOMAIN}

  # XMPP server
  prosody:
    image: jitsi/prosody
    container_name: jitsi-prosody
    expose:
      - '5222'
      - '5347'
      - '5280'
    volumes:
      - ${CONFIG}/prosody:/config
    environment:
      - AUTH_TYPE
      - ENABLE_AUTH
      - ENABLE_GUESTS
      - GLOBAL_MODULES
      - GLOBAL_CONFIG
      - LDAP_URL
      - LDAP_BASE
      - LDAP_BINDDN
      - LDAP_BINDPW
      - LDAP_FILTER
      - LDAP_AUTH_METHOD
      - LDAP_VERSION
      - LDAP_USE_TLS
      - LDAP_TLS_CIPHERS
      - LDAP_TLS_CHECK_PEER
      - LDAP_TLS_CACERT_FILE
      - LDAP_TLS_CACERT_DIR
      - LDAP_START_TLS
      - XMPP_DOMAIN
      - XMPP_AUTH_DOMAIN
      - XMPP_GUEST_DOMAIN
      - XMPP_MUC_DOMAIN
      - XMPP_INTERNAL_MUC_DOMAIN
      - XMPP_MODULES
      - XMPP_MUC_MODULES
      - XMPP_INTERNAL_MUC_MODULES
      - XMPP_RECORDER_DOMAIN
      - JICOFO_COMPONENT_SECRET
      - JICOFO_AUTH_USER
      - JICOFO_AUTH_PASSWORD
      - JVB_AUTH_USER
      - JVB_AUTH_PASSWORD
      - JIGASI_XMPP_USER
      - JIGASI_XMPP_PASSWORD
      - JIBRI_XMPP_USER
      - JIBRI_XMPP_PASSWORD
      - JIBRI_RECORDER_USER
      - JIBRI_RECORDER_PASSWORD
      - JWT_APP_ID
      - JWT_APP_SECRET
      - JWT_ACCEPTED_ISSUERS
      - JWT_ACCEPTED_AUDIENCES
      - JWT_ASAP_KEYSERVER
      - JWT_ALLOW_EMPTY
      - JWT_AUTH_TYPE
      - JWT_TOKEN_AUTH_MODULE
      - LOG_LEVEL
      - TZ
    networks:
      nextcloud_network:
          aliases:
            - ${XMPP_SERVER}

  # Focus component
  jicofo:
    image: jitsi/jicofo
    container_name: jitsi-jicofo
    volumes:
      - ${CONFIG}/jicofo:/config
    environment:
      - ENABLE_AUTH
      - XMPP_DOMAIN
      - XMPP_AUTH_DOMAIN
      - XMPP_INTERNAL_MUC_DOMAIN
      - XMPP_SERVER
      - JICOFO_COMPONENT_SECRET
      - JICOFO_AUTH_USER
      - JICOFO_AUTH_PASSWORD
      - JICOFO_RESERVATION_REST_BASE_URL
      - JVB_BREWERY_MUC
      - JIGASI_BREWERY_MUC
      - JIGASI_SIP_URI
      - JIBRI_BREWERY_MUC
      - JIBRI_PENDING_TIMEOUT
      - TZ
    depends_on:
      - prosody
    networks:
      nextcloud_network:

  # Video bridge
  jvb:
    image: jitsi/jvb
    container_name: jitsi-jvb
    ports:
      - '${JVB_PORT}:${JVB_PORT}/udp'
      - '${JVB_TCP_PORT}:${JVB_TCP_PORT}'
    volumes:
      - ${CONFIG}/jvb:/config
    environment:
      - DOCKER_HOST_ADDRESS
      - XMPP_AUTH_DOMAIN
      - XMPP_INTERNAL_MUC_DOMAIN
      - XMPP_SERVER
      - JVB_AUTH_USER
      - JVB_AUTH_PASSWORD
      - JVB_BREWERY_MUC
      - JVB_PORT
      - JVB_TCP_HARVESTER_DISABLED
      - JVB_TCP_PORT
      - JVB_STUN_SERVERS
      - JVB_ENABLE_APIS
      - TZ
    depends_on:
      - prosody
    networks:
      nextcloud_network:

# Custom network so all services can communicate using a FQDN
# changed the network name - the network below was already in place and jitsi needs to be in the same network as my reverse proxy
networks:
  nextcloud_network:
```

What am I missing?
