### ISSUE TITLE
Add the ability to just use the jibri composant in docker

### ISSUE THREAD

**Issue by yodatak** [jitsi/docker-jitsi-meet#416]
It cloud be interesting to just have the jibri composant to a docker image and document how to use it because install a chromium stack in a production server is not the best in docker its just fine !

**Comment by akramer-zibra** [comment]
The `Dockerfile` file in the [jibri](https://github.com/jitsi/docker-jitsi-meet/tree/master/jibri) subfolder should do the trick. Use `docker build ...` to create an image from that Dockerfile. You'll find this image also on the docker hub [jitsi/jibri](https://hub.docker.com/r/jitsi/jibri)

**Comment by lggwettmann** [comment]
Sorry for this docker-noob question:
Would it also work to eg. just pull the docker image from the docker hub and run it? Or which steps do I still need to do to make this work once I installed docker on my server?

**Comment by akramer-zibra** [comment]
> Would it also work to eg. just pull the docker image from the docker hub and run it?

Yes, I think so. You should be able to run e.g. the jibri docker images also standalone. The configuration is done via ENVIRONMENT-Variables. You'll find the available variables in the [jibri.yml](https://github.com/jitsi/docker-jitsi-meet/blob/master/jibri.yml) and described in the [README.md](https://github.com/jitsi/docker-jitsi-meet#jitsi-broadcasting-infrastructure-configuration)

If you need more custom configuration build yor own jibri docker image with the files from the [jibri](https://github.com/jitsi/docker-jitsi-meet/tree/master/jibri) subfolder

**Comment by hmharshit** [comment]
It's possible to jibri container as standalone. You just need to have proper *.env* file mentioned in the README.md with minor customization in the jibri.yml.

This is the jibri.yml which I'm using to run jibri in separate VMs, all communicating with one main prosody server,

```
 
version: '3'

services:
    jibri:
        image: jitsi/jibri
        volumes:
            - ${CONFIG}/jibri:/config
            - /dev/shm:/dev/shm
        cap_add:
            - SYS_ADMIN
            - NET_BIND_SERVICE
        devices:
            - /dev/snd:/dev/snd
        environment:
            - XMPP_AUTH_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_RECORDER_DOMAIN
            - XMPP_SERVER
            - XMPP_DOMAIN
            - JIBRI_XMPP_USER
            - JIBRI_XMPP_PASSWORD
            - JIBRI_BREWERY_MUC
            - JIBRI_RECORDER_USER
            - JIBRI_RECORDER_PASSWORD
            - JIBRI_RECORDING_DIR
            - JIBRI_FINALIZE_RECORDING_SCRIPT_PATH
            - JIBRI_STRIP_DOMAIN_JID
            - JIBRI_LOGS_DIR
            - DISPLAY=:0
            - TZ
```

Remember, proper configuration is required to be done in the .env file for the jibri to communicate with the XMPP server.
