### ISSUE TITLE
Screensharing not working

### ISSUE THREAD

**Issue by ybabel** [jitsi/docker-jitsi-meet#45]
Hello, 
the containers works well, I'm able to launch jitsi meet, but the screen-sharing (which is working on a demo server) is not enabled.
I could not figure out if it was missing or a configuration issue (I'm new to jitsi).

**Comment by saghul** [comment]
I assume you were using Chrome. You need an extension, that's a Chrome limitation. However this limitation disappears in Chrome 72 (to be released this week, so you can try Chrome beta).

**Comment by ybabel** [comment]
No I did not used chrome, but Firefox. I should have specified it. I have reinstalled jitsi, properly (with docker compose) and now it work ... but now jitsi android don't work at all, and the screensharing sometimes work, sometime don't ... very frustrating.

**Comment by saghul** [comment]
Can you be a mit more specific? How does it not work? Do you see a blank screen? Something else? Do you see any errors in the JS console?

As for the mobile apps, are you using a Let's Encrypt certificate or a self-signed one? Self-signed certificates don't work with the mobile apps.

**Comment by ybabel** [comment]
As for the screensharing, I had it work mostly for a shell window. Other windows I could not make it work. Video seems to work between my 2 PC when I tested it.

For the mobile, I think I use let's encrypt, but maybe my configuration is incorrect.
There it is (I changed the domain name). I use traefik  : 
```
version: '3'

services:
    # Frontend
    web:
        image: jitsi/web
        #ports:
        #    - '${HTTP_PORT}:80'
        #    - '${HTTPS_PORT}:443'
        volumes:
            - ${CONFIG}/web:/config
        environment:
            - ENABLE_AUTH
            - ENABLE_GUESTS
            - ENABLE_LETSENCRYPT
            - ENABLE_HTTP_REDIRECT
            - DISABLE_HTTPS
            - JICOFO_AUTH_USER
            - LETSENCRYPT_DOMAIN
            - LETSENCRYPT_EMAIL
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_BOSH_URL_BASE=http://xmpp.meet.jitsi:5280
            - XMPP_GUEST_DOMAIN
            - XMPP_MUC_DOMAIN
            - TZ
        networks:
            - traefik
            - meet.jitsi
        labels:
            - "traefik.docker.network=traefik"
            - "traefik.frontend.rule=Host:video.athome.fr"
            - "traefik.frontend.port:80"
            - "traefik.backend.rule=Host:video.athome.fr"
            - "traefik.backend.port:443"

    # XMPP server
    prosody:
        image: jitsi/prosody
        expose:
            - '5222'
            - '5347'
            - '5280'
        volumes:
            - ${CONFIG}/prosody:/config
        environment:
            - ENABLE_AUTH
            - ENABLE_GUESTS
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_GUEST_DOMAIN
            - XMPP_MUC_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - JICOFO_COMPONENT_SECRET
            - JICOFO_AUTH_USER
            - JICOFO_AUTH_PASSWORD
            - JVB_AUTH_USER
            - JVB_AUTH_PASSWORD
            - JIGASI_XMPP_USER
            - JIGASI_XMPP_PASSWORD
            - TZ
        networks:
            meet.jitsi:
                aliases:
                    - xmpp.meet.jitsi

    # Focus component
    jicofo:
        image: jitsi/jicofo
        volumes:
            - ${CONFIG}/jicofo:/config
        environment:
            - ENABLE_AUTH
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_SERVER=xmpp.meet.jitsi
            - JICOFO_COMPONENT_SECRET
            - JICOFO_AUTH_USER
            - JICOFO_AUTH_PASSWORD
            - JVB_BREWERY_MUC
            - JIGASI_BREWERY_MUC
            - TZ
        depends_on:
            - prosody
        networks:
            - meet.jitsi

    # Video bridge
    jvb:
        image: jitsi/jvb
        ports:
            - '${JVB_PORT}:${JVB_PORT}/udp'
            - '${JVB_TCP_PORT}:${JVB_TCP_PORT}'
        volumes:
            - ${CONFIG}/jvb:/config
        environment:
            - DOCKER_HOST_ADDRESS
            - XMPP_AUTH_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_SERVER=xmpp.meet.jitsi
            - JVB_AUTH_USER
            - JVB_AUTH_PASSWORD
            - JVB_BREWERY_MUC
            - JVB_PORT
            - JVB_TCP_HARVESTER_DISABLED
            - JVB_TCP_PORT
            - JVB_STUN_SERVERS
            - JVB_ENABLE_APIS
            - JICOFO_AUTH_USER
            - TZ
        depends_on:
            - prosody
        networks:
            - meet.jitsi

# Custom network so all services can communicate using a FQDN
networks:
  meet.jitsi:
      external: false
  traefik:
    external:
      name: traefik
```
and the env file : 
```
#
# Basic configuration options
#

# Directory where all configuration will be stored.
CONFIG=~/.jitsi-meet-cfg

# Exposed HTTP port.
HTTP_PORT=80

# Exposed HTTPS port.
HTTPS_PORT=443

# System time zone.
TZ=Europe/Paris

# IP address of the Docker host. See the "Running on a LAN environment" section
# in the README.
#DOCKER_HOST_ADDRESS=51.75.125.107


#
# Let's Encrypt configuration
#

# Enable Let's Encrypt certificate generation.
ENABLE_LETSENCRYPT=1

# Domain for which to generate the certificate.
LETSENCRYPT_DOMAIN=video.athome.fr

# E-Mail for receiving important account notifications (mandatory).
LETSENCRYPT_EMAIL=ybabel@free.fr


#
# Basic Jigasi configuration options (needed for SIP gateway support)
#

# SIP URI for incoming / outgoing calls.
JIGASI_SIP_URI=test@sip2sip.info

# Password for the specified SIP account as a clear text
JIGASI_SIP_PASSWORD=passw0rd

# SIP server (use the SIP account domain if in doubt).
JIGASI_SIP_SERVER=sip2sip.info

# SIP server port
JIGASI_SIP_PORT=5060

# SIP server transport
JIGASI_SIP_TRANSPORT=UDP

#
# Authentication configuration (see README for details)
#

# Enable authentication.
#ENABLE_AUTH=1

# Enable guest access.
#ENABLE_GUESTS=1

#
# Advanced configuration options (you generally don't need to change these)
#

# Internal XMPP domain.
XMPP_DOMAIN=meet.jitsi

# Internal XMPP domain for authenticated services.
XMPP_AUTH_DOMAIN=auth.meet.jitsi

# XMPP domain for the MUC.
XMPP_MUC_DOMAIN=muc.meet.jitsi

# XMPP domain for the internal MUC used for jibri, jigasi and jvb pools.
XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi

# XMPP domain for unauthenticated users.
XMPP_GUEST_DOMAIN=guest.meet.jitsi

# MUC for the JVB pool.
JVB_BREWERY_MUC=jvbbrewery

# XMPP user for JVB client connections.
JVB_AUTH_USER=jvb

# XMPP password for JVB client connections.
JVB_AUTH_PASSWORD=passw0rd

# STUN servers used to discover the server's public IP.
JVB_STUN_SERVERS=stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302

# Media port for the Jitsi Videobridge
JVB_PORT=10000

# TCP Fallback for Jitsi Videobridge for when UDP isn't available
JVB_TCP_HARVESTER_DISABLED=true
JVB_TCP_PORT=4443

# A comma separated list of APIs to enable when the JVB is started. The default is none.
# See https://github.com/jitsi/jitsi-videobridge/blob/master/doc/rest.md for more information
#JVB_ENABLE_APIS=rest,colibri

# XMPP component password for Jicofo.
JICOFO_COMPONENT_SECRET=s3cr37

# XMPP user for Jicofo client connections. NOTE: this option doesn't currently work due to a bug.
JICOFO_AUTH_USER=focus

# XMPP password for Jicofo client connections.
JICOFO_AUTH_PASSWORD=passw0rd

# XMPP user for Jigasi MUC client connections.
JIGASI_XMPP_USER=jigasi

# XMPP password for Jigasi MUC client connections.
JIGASI_XMPP_PASSWORD=passw0rd

# MUC name for the Jigasi pool.
JIGASI_BREWERY_MUC=jigasibrewery

# Minimum port for media used by Jigasi.
JIGASI_PORT_MIN=20000

# Maximum port for media used by Jigasi.
JIGASI_PORT_MAX=20050

# Disable HTTPS. This can be useful if TLS connections are going to be handled outside of this setup.
DISABLE_HTTPS=1

# Redirects HTTP traffic to HTTPS. Only works with the standard HTTPS port (443).
#ENABLE_HTTP_REDIRECT=1
```

Should I change DISABLE_HTTPS ?
Should I clean ~/.jitsi-meet-cfg ? maybe it contains a previous version of my configuration ? (I didn't make jitsi work the first time I tried)
