### ISSUE TITLE
[Docker-Swarm][Traefik]Enable_Guests isn't working if using Traefik with docker-swarm setup

### ISSUE THREAD

**Issue by prayagsingh** [jitsi/docker-jitsi-meet#538]
I’m trying to enable the authentication by setting below parameters in compose.yaml file using with docker swarm but I’m geeting 502 error in console logs. Every service in swarm is running on different VM.
```
# Enable authentication
ENABLE_AUTH=1

# Enable guest access
ENABLE_GUESTS=1

# Select authentication type: internal, jwt or ldap
AUTH_TYPE=internal
```
I was following this link: following link: https://github.com/jitsi/docker-jitsi-meet#authentication

**compose file for docker swarm**
```
version: '3.8'

services:
    # Frontend
    web:
        image: jitsi/web
        environment:
            ENABLE_AUTH: 1
            ENABLE_GUESTS: 1
            ENABLE_RECORDING: 1
            ENABLE_TRANSCRIPTIONS:
            ETHERPAD_URL_BASE:
            DISABLE_HTTPS: 1
            JICOFO_AUTH_USER: focus
            PUBLIC_URL: https://meet.example.in
            XMPP_DOMAIN: meet.example.in
            XMPP_AUTH_DOMAIN: auth.meet.example.in
            XMPP_BOSH_URL_BASE: http://xmpp.meet.example.in:5280
            XMPP_GUEST_DOMAIN: guest.meet.example.in
            XMPP_MUC_DOMAIN: muc.meet.example.in
            XMPP_RECORDER_DOMAIN: recorder.meet.example.in
            TZ: Asia/Kolkata
            JIBRI_BREWERY_MUC: jibribrewery
            JIBRI_PENDING_TIMEOUT: 90
            JIBRI_XMPP_USER: jibri
            JIBRI_XMPP_PASSWORD: 160135fb81b8f78232b26df486880b81
            JIBRI_RECORDER_USER: recorder
            JIBRI_RECORDER_PASSWORD: 46ea1b0e6252479eb6cc647bed7cfc18
        deploy:
          replicas: 1
          update_config:
            failure_action: rollback
          restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 5
          placement:
            constraints:
              - node.hostname != vs1
              - node.role == manager

          labels:
            - "traefik.enable=true"
            - "traefik.docker.network=proxy"
            ### http
            - "traefik.http.routers.jitsi.entrypoints=web"
            - "traefik.http.routers.jitsi.rule=Host(`meet.example.in`)"
            ### https
            - "traefik.http.routers.jitsi-secure.entrypoints=websecure"
            - "traefik.http.routers.jitsi-secure.rule=Host(`meet.example.in`)"
            ### assigning middleware
            - "traefik.http.routers.jitsi.middlewares=jitsi-https-redirect"
            ### assigning service
            - "traefik.http.routers.jitsi-secure.service=jitsi" #here service name is jitsi

            ## Middleware
            - "traefik.http.middlewares.jitsi-https-redirect.redirectscheme.scheme=https"
            - "traefik.http.middlewares.jitsi-https-redirect.redirectscheme.permanent=true"
            
            ## LetsEncrypt
            - "traefik.http.routers.jitsi-secure.tls=true"
            - "traefik.http.routers.jitsi-secure.tls.certresolver=letsencrypt"
            - "traefik.http.routers.jitsi-secure.tls.domains[0].main=meet.example.in"

            ## Service
            - "traefik.http.services.jitsi.loadbalancer.server.port=80"

        volumes:
            - ${CONFIG}/web:/config

        ports:
            - target: 80
        networks:
          proxy:
          jitsi:
            aliases:
                    #- web.meet.example.in
              - meet.example.in

    # XMPP server
    prosody:
        image: jitsi/prosody
        hostname: xmpp.meet.example.in
        deploy:
          replicas: 1
          update_config:
            failure_action: rollback
          restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 5
          placement:
            constraints: [node.hostname != vs1]
        environment:
            AUTH_TYPE: internal
            ENABLE_AUTH: 1
            GLOBAL_CONFIG:
            GLOBAL_MODULES:
            LDAP_AUTH_METHOD:
            LDAP_URL:
            LDAP_TLS_CACERT_FILE:
            LDAP_TLS_CACERT_DIR:
            LDAP_BINDPW:
            LDAP_FILTER:
            LDAP_TLS_CHECK_PEER:
            LDAP_START_TLS:
            LDAP_VERSION:
            JICOFO_COMPONENT_SECRET: e7f79f7a16a1b6a8bd5c18327d9bdace
            JICOFO_AUTH_USER: focus
            JICOFO_AUTH_PASSWORD: b44d6f8dd2af24a03fded73ebaa3ae2a
            JVB_AUTH_USER: jvb
            JVB_AUTH_PASSWORD: f8412a7d2f9821e8e9313fb6dad86a02
            PUBLIC_URL: https://meet.example.in
            XMPP_DOMAIN: meet.example.in
            XMPP_AUTH_DOMAIN: auth.meet.example.in
            XMPP_BOSH_URL_BASE: http://xmpp.meet.example.in:5280
            XMPP_GUEST_DOMAIN: guest.meet.example.in
            XMPP_MUC_DOMAIN: muc.meet.example.in
            XMPP_INTERNAL_MUC_DOMAIN: internal-muc.meet.example.in
            XMPP_RECORDER_DOMAIN: recorder.meet.example.in
            XMPP_MODULES:
            XMPP_MUC_MODULES:
            XMPP_INTERNAL_MUC_MODULES:
            TZ: Asia/Kolkata
            JIGASI_XMPP_USER: jigasi
            JIGASI_XMPP_PASSWORD: 1c59269877257b39cc0475b21cf08a16
            JIBRI_BREWERY_MUC: jibribrewery
            JIBRI_PENDING_TIMEOUT: 90
            JIBRI_XMPP_USER: jibri
            JIBRI_XMPP_PASSWORD: 160135fb81b8f78232b26df486880b81
            JIBRI_RECORDER_USER: recorder
            JIBRI_RECORDER_PASSWORD: 46ea1b0e6252479eb6cc647bed7cfc18
            JWT_APP_ID:
            JWT_APP_SECRET: something long goes here
            JWT_ACCEPTED_ISSUERS:
            JWT_ALLOW_EMPTY:
            JWT_AUTH_TYPE:
            JWT_TOKEN_AUTH_MODULE:
            JWT_ACCEPTED_AUDIENCES:
            JWT_ASAP_KEYSERVER:
            LOG_LEVEL: Debug
        volumes:
            - ${CONFIG}/prosody:/config
            - ${CONFIG}/prosody:/etc/prosody

        ports:
            - target: 5222
              published: 5222
              #mode: host
            - target: 5347
              published: 5347
              #mode: host
            - target: 5280
              published: 5280
              #mode: host

        networks:
          jitsi:
             aliases:
                     #- meet.example.in
               - xmpp.meet.example.in
                 #- auth.meet.example.in
                 #- guest.meet.example.in
                 #- muc.meet.example.in
                 #- internal-muc.meet.example.in
                 #- focus.meet.example.in

    # Focus component
    jicofo:
        image: jitsi/jicofo

        deploy:
          replicas: 1
          update_config:
            failure_action: rollback
          restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 5
          placement:
            constraints: [node.hostname != vs1]
        environment:
            ENABLE_AUTH: 1
            JICOFO_COMPONENT_SECRET: e7f79f7a16a1b6a8bd5c18327d9bdace
            JICOFO_AUTH_USER: focus
            JICOFO_AUTH_PASSWORD: b44d6f8dd2af24a03fded73ebaa3ae2a
            JICOFO_RESERVATION_REST_BASE_URL:
            XMPP_DOMAIN: meet.example.in
            XMPP_AUTH_DOMAIN: auth.meet.example.in
            XMPP_INTERNAL_MUC_DOMAIN: internal-muc.meet.example.in
            XMPP_SERVER: xmpp.meet.example.in
            TZ: Asia/Kolkata
            JIBRI_BREWERY_MUC: jibribrewery
            JIBRI_PENDING_TIMEOUT: 90
            JVB_BREWERY_MUC: jvbbrewery
            JIGASI_BREWERY_MUC: jigasibrewery
        depends_on:
            - prosody
        volumes:
            - ${CONFIG}/jicofo:/config
        networks:
            jitsi:

    # Video bridge
    jvb:
        image: jitsi/jvb
        ports:
          - target: 10000
            published: 10000
            #mode: host
            protocol: udp
          - target: 4443
            published: 4443
            #mode: host
            protocol: tcp

        deploy:
          replicas: 1
          rollback_config:
            parallelism: 1
            delay: 5s
            failure_action: continue
            monitor: 10s
            order: stop-first
          update_config:
            parallelism: 1
            delay: 5s
            failure_action: rollback
            order: start-first
          restart_policy:
            condition: on-failure
            delay: 5s
            #max_attempts: 5
          placement:
            max_replicas_per_node: 1
            constraints:
              - "node.hostname!=vs1"
              - "node.role==worker"

        environment:
            XMPP_INTERNAL_MUC_DOMAIN: internal-muc.meet.example.in
            XMPP_AUTH_DOMAIN: auth.meet.example.in
            XMPP_SERVER: xmpp.meet.example.in
            TZ: Asia/Kolkata
            JIBRI_BREWERY_MUC: jibribrewery
            JIBRI_PENDING_TIMEOUT: 90
            JVB_AUTH_USER: jvb
            JVB_AUTH_PASSWORD: f8412a7d2f9821e8e9313fb6dad86a02
            JVB_BREWERY_MUC: jvbbrewery
            JVB_PORT: 10000
            JVB_TCP_HARVESTER_DISABLED: 0
            JVB_TCP_PORT: 4443
            JVB_STUN_SERVERS: stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302
            JVB_ENABLE_APIS: rest,colibri
        depends_on:
            - prosody
        volumes:
            - ${CONFIG}/jvb:/config
        networks:
            jitsi:
              aliases:
                - jvb.meet.example.in


# Custom network so all services can communicate using a FQDN
networks:
  proxy:
    external: true
    name: proxy
  jitsi:
    external: true    
    name: jitsi
```
**Traefik.yaml file**
```
version: '3.8'

services:

  traefik:
    image: "traefik:v2.2"
    hostname: "traefik"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      placement:
        constraints:
          - node.hostname == vs1
          - node.role == manager
    command:
      - --api=true
      - --api.dashboard=true
      - --api.debug=true
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --log.level=DEBUG
      - --accesslog=false
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      ## LetsEncrypt
      #- --certificatesResolvers.letsencrypt.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesResolvers.letsencrypt.acme.tlsChallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=myemail@gmail.com
      - --certificatesResolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
        #- --certificatesResolvers.letsencrypt.acme.httpChallenge.entryPoint=web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
        #- "traefik.http.services.dummyService.loadbalancer.server.port=1111" # In swarm mode, traefik requires a dummy Port
      - "traefik.http.routers.api.rule=Host(`traefik.example.in`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth,httpsalways"
      
      ## Middlewares
      - "traefik.http.middlewares.auth.basicauth.users=alpha:$$apr1$$Bz.UZC1x$$.joBaPFxh5M64dzTYMiNv0"

      ### host header
      #- "traefik.http.middlewares.hosthdr.headers.stsseconds=31536000"
      #- "traefik.http.middlewares.hosthdr.headers.stsincludesubdomains=true"
      #- "traefik.http.middlewares.hosthdr.headers.stspreload=true"

      # middleware redirect http to https
      - "traefik.http.middlewares.httpsalways.redirectscheme.scheme=https"
      - "traefik.http.middlewares.httpsalways.redirectscheme.permanent=true"
      - "traefik.http.middlewares.httpsalways.redirectscheme.port=443"

      # enable https for api/dashboard
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.domains[0].main=traefik.example.in"
    ports:
      - target: 80
        #published: 80
        mode: host

      - target: 443
        published: 443
        mode: host

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"
#- "./basicauth:/basicauth:ro"
    networks:
      - proxy

networks:
  proxy:
    external: true
    #name: proxy
```

**web container logs**
```
jitsi_web.1.kbo0ujq3mwsp@vs2    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
jitsi_web.1.kbo0ujq3mwsp@vs2    | [s6-init] ensuring user provided files have correct perms...exited 0.
jitsi_web.1.kbo0ujq3mwsp@vs2    | [fix-attrs.d] applying ownership & permissions fixes...
jitsi_web.1.kbo0ujq3mwsp@vs2    | [fix-attrs.d] done.
jitsi_web.1.kbo0ujq3mwsp@vs2    | [cont-init.d] executing container initialization scripts...
jitsi_web.1.kbo0ujq3mwsp@vs2    | [cont-init.d] 01-set-timezone: executing...
jitsi_web.1.kbo0ujq3mwsp@vs2    | [cont-init.d] 01-set-timezone: exited 0.
jitsi_web.1.kbo0ujq3mwsp@vs2    | [cont-init.d] 10-config: executing...
jitsi_web.1.kbo0ujq3mwsp@vs2    | [cont-init.d] 10-config: exited 0.
jitsi_web.1.kbo0ujq3mwsp@vs2    | [cont-init.d] done.
jitsi_web.1.kbo0ujq3mwsp@vs2    | [services.d] starting services
jitsi_web.1.kbo0ujq3mwsp@vs2    | [services.d] done.
jitsi_web.1.kbo0ujq3mwsp@vs2    | nginx: [emerg] host not found in upstream "xmpp.meet.example.in" in /config/nginx/meet.conf:35
jitsi_web.1.kbo0ujq3mwsp@vs2    | nginx: [emerg] host not found in upstream "xmpp.meet.example.in" in /config/nginx/meet.conf:35
jitsi_web.1.kbo0ujq3mwsp@vs2    | nginx: [emerg] host not found in upstream "xmpp.meet.example.in" in /config/nginx/meet.conf:35
jitsi_web.1.kbo0ujq3mwsp@vs2    | nginx: [emerg] host not found in upstream "xmpp.meet.example.in" in /config/nginx/meet.conf:35
jitsi_web.1.kbo0ujq3mwsp@vs2    | 10.0.4.73 - - [01/May/2020:13:37:34 +0530] "GET / HTTP/1.1" 200 13616 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36"
jitsi_web.1.kbo0ujq3mwsp@vs2    | 10.0.4.73 - - [01/May/2020:13:37:35 +0530] "GET /libs/do_external_connect.min.js?v=1 HTTP/1.1" 200 2418 "https://meet.example.in/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36"
jitsi_web.1.kbo0ujq3mwsp@vs2    | 10.0.4.73 - - [01/May/2020:13:37:35 +0530] "GET /libs/lib-jitsi-meet.min.js?v=3992 HTTP/1.1" 200 747943 "https://meet.example.in/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36"
jitsi_web.1.kbo0ujq3mwsp@vs2    | 10.0.4.73 - - [01/May/2020:13:37:36 +0530] "GET /libs/app.bundle.min.js?v=3992 HTTP/1.1" 200 2912310 "https://meet.example.in/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36"
jitsi_web.1.kbo0ujq3mwsp@vs2    | 10.0.4.73 - - [01/May/2020:13:37:40 +0530] "GET /test HTTP/1.1" 200 13616 "https://meet.example.in/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36"
jitsi_web.1.kbo0ujq3mwsp@vs2    | 10.0.4.73 - - [01/May/2020:13:37:40 +0530] "GET /libs/do_external_connect.min.js?v=1 HTTP/1.1" 200 2418 "https://meet.example.in/test" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36"
jitsi_web.1.kbo0ujq3mwsp@vs2    | 10.0.4.73 - - [01/May/2020:13:37:40 +0530] "GET /libs/lib-jitsi-meet.min.js?v=3992 HTTP/1.1" 200 747944 "https://meet.example.in/test" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36"
jitsi_web.1.kbo0ujq3mwsp@vs2    | 10.0.4.73 - - [01/May/2020:13:37:41 +0530] "GET /libs/app.bundle.min.js?v=3992 HTTP/1.1" 200 2912304 "https://meet.example.in/test" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36"
jitsi_web.1.kbo0ujq3mwsp@vs2    | 10.0.4.73 - - [01/May/2020:13:37:42 +0530] "POST /http-bind?room=test HTTP/1.1" 200 395 "https://meet.example.in/test" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36"
jitsi_web.1.kbo0ujq3mwsp@vs2    | 10.0.4.73 - - [01/May/2020:13:38:08 +0530] "GET /libs/app.bundle.min.map HTTP/1.1" 200 10384446 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36"
jitsi_web.1.kbo0ujq3mwsp@vs2    | 2020/05/01 13:38:42 [error] 270#270: *2 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.0.4.73, server: _, request: "POST /http-bind?room=test HTTP/1.1", upstream: "http://10.0.10.98:5280/http-bind?room=test", host: "meet.example.in", referrer: "https://meet.example.in/test"
jitsi_web.1.kbo0ujq3mwsp@vs2    | 10.0.4.73 - - [01/May/2020:13:38:42 +0530] "POST /http-bind?room=test HTTP/1.1" 504 590 "https://meet.example.in/test" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36"
jitsi_web.1.kbo0ujq3mwsp@vs2    | 10.0.4.73 - - [01/May/2020:13:38:42 +0530] "POST /http-bind?room=test HTTP/1.1" 200 148 "https://meet.example.in/test" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36"
```

**console log screenshot**
![Screenshot (195)](https://user-images.githubusercontent.com/8455114/80800135-5b505c00-8bc6-11ea-9598-f2806328cb76.png)
