### ISSUE TITLE
What is jitsi video bridge port number?

### ISSUE THREAD

**Issue by elcolie** [jitsi/docker-jitsi-meet#61]
What is the default `JVB_PORT and JVB_TCP_PORT` number?
I have to configure inbound policy
```
    jvb:
        image: jitsi/jvb
        ports:
            - '${JVB_PORT}:${JVB_PORT}/udp'
            - '${JVB_TCP_PORT}:${JVB_TCP_PORT}'
```
