### ISSUE TITLE
Kubernetes deployment: guest domain not properly configured in jitsi-meet container configuration

### ISSUE THREAD

**Issue by JohnLukeP** [jitsi/docker-jitsi-meet#772]
Hi, I'm trying to deploy Jitsi meet on a IBM Cloud's Kubernetes cluster, based on the instructions at:
https://github.com/jitsi/docker-jitsi-meet/tree/master/examples/kubernetes
but the unauthenticated guest domain doesn't get applied correctyly.

In details I've tried implementing the JWT authentication, by adding (just as in the docker container deployment) to the deployment.yaml chart's Prosody container ENV section:              

            - name: XMPP_GUEST_DOMAIN
              value: guest.meet.jitsi
            - name: XMPP_MUC_DOMAIN
              value: muc.meet.jitsi
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.jitsi
            - name: ENABLE_AUTH
              value: "1"
            - name: ENABLE_GUESTS
              value: "1"
            - name: AUTH_TYPE
              value: "jwt"
            - name: JWT_APP_ID
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JWT_APP_ID
            - name: JWT_APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JWT_APP_SECRET

Moreover, I've added to every other other containers ENV sections (jicofo,web,jvb):

```
           - name: XMPP_GUEST_DOMAIN
              value: guest.meet.jitsi
```

When I apply this chart, the JWT token authentication gets enabled on the prosody's virtualhost config and in fact works, and in the prosody container domain.cfg.lua file the guest domain is present:

```
VirtualHost "meet.jitsi"

    authentication = "token"
    app_id = "JitsiVideoOpenSquare"
    app_secret = "*********"
    allow_empty_token = false
```
And:

```
VirtualHost "guest.meet.jitsi"
    authentication = "anonymous"
    c2s_require_encryption = false
```

The problem resides in the web container's config.js file, which shows:

```
hosts: {
        // XMPP domain.
        domain: 'jitsi-meet.example.com',

        // When using authentication, domain for guest users.
        // anonymousdomain: 'guest.example.com',

        // Domain for authenticated users. Defaults to <domain>.
        // authdomain: 'jitsi-meet.example.com',

        // Call control component (Jigasi).
        // call_control: 'callcontrol.jitsi-meet.example.com',

        // Focus component domain. Defaults to focus.<domain>.
        // focus: 'focus.jitsi-meet.example.com',

        // XMPP MUC domain. FIXME: use XEP-0030 to discover it.
        muc: 'conference.jitsi-meet.example.com'
    },
```
As you can see the guest domain part is not getting uncommented.
This leads to the problem that guests cannot join rooms already created by authenticated (via JWT) users.
What am I missing?

### Steps to reproduce:

1. Deploy jitsi-meet on kubernetes enabling the JWT authentication and guest domain
2. Create a room from a JWT authenticated user
3. Share the link to guests

### Expected behavior:

Guests are allowed to enter  the already created room

### Actual behavior:

Guests are asked for basic authentication even though the room is already created

**Comment by JohnLukeP** [comment]
I tried manually changing with sed in the running container

// anonymousdomain: 'guest.example.com',

to

anonymousdomain: 'guest.example.com',

But if I do so, guests trying to join are not prompted with "the conference has not yet started". It shows only the standard conference page, with cam and video disabled, so I guess it's not working either.

What is missing to enable the guest domain and JWT authentication together, just as in the docker deployment which works perfectly?

**Comment by rojenzaman** [comment]
I have the same problem in kubernetes with rancher, did you solve it?

please visit: https://github.com/jitsi/docker-jitsi-meet/issues/790

**Comment by JohnLukeP** [comment]
> I have the same problem with LDAP in kubernetes with rancher, did you solve it?
> 
> please visit: #790

Hi, I don't know Rancher, but I did three things, don't actually now which one fixed them but here's what I did:

1. used version 4857 instead of latest
2. Wiped out the entire kubernetes cluster, as I thought some configs were not properly deleted when deleting the Jitsi deployment
3. Modified the deployment.yaml that I got from https://github.com/jitsi/docker-jitsi-meet/tree/master/examples/kubernetes n the following way.


```
apiVersion: apps/v1
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: jitsi
  name: jitsi
  namespace: jitsi
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      k8s-app: jitsi
  template:
    metadata:
      labels:
        k8s-app: jitsi
    spec:
      containers:
        - name: jicofo
          image: jitsi/jicofo
          imagePullPolicy: Always
          env:
            - name: XMPP_SERVER
              value: localhost
            - name: ENABLE_GUESTS
              value: "1"
            - name: XMPP_DOMAIN
              value: meet.jitsi
            - name: XMPP_GUEST_DOMAIN
              value: guest.meet.jitsi
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.jitsi
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.jitsi
            - name: JICOFO_COMPONENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_COMPONENT_SECRET
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_AUTH_PASSWORD
            - name: TZ
              value: Europe/Rome
            - name: JVB_BREWERY_MUC
              value: jvbbrewery
        - name: prosody
          image: jitsi/prosody
          imagePullPolicy: Always
          env:
            - name: XMPP_DOMAIN
              value: meet.jitsi
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.jitsi
            - name: XMPP_GUEST_DOMAIN
              value: guest.meet.jitsi
            - name: XMPP_MUC_DOMAIN
              value: muc.meet.jitsi
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.jitsi
            - name: ENABLE_AUTH
              value: "1"
            - name: ENABLE_GUESTS
              value: "1"
            - name: AUTH_TYPE
              value: "jwt"
            - name: JWT_APP_ID
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JWT_APP_ID
            - name: JWT_APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JWT_APP_SECRET
            - name: JICOFO_COMPONENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_COMPONENT_SECRET
            - name: JVB_AUTH_USER
              value: jvb
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JVB_AUTH_PASSWORD
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_AUTH_PASSWORD
            - name: TZ
              value: Europe/Rome
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "true"           
        - name: web
          image: jitsi/web
          imagePullPolicy: Always
          env:
            - name: XMPP_SERVER
              value: localhost
            - name: JICOFO_AUTH_USER
              value: focus
            - name: XMPP_DOMAIN
              value: meet.jitsi
            - name: ENABLE_GUESTS
              value: "1"
            - name: XMPP_GUEST_DOMAIN
              value: guest.meet.jitsi
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.jitsi
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.jitsi
            - name: XMPP_BOSH_URL_BASE
              value: http://127.0.0.1:5280
            - name: XMPP_MUC_DOMAIN
              value: muc.meet.jitsi
            - name: TZ
              value: Europe/Rome
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "true"
        - name: jvb
          image: jitsi/jvb
          imagePullPolicy: Always
          env:
            - name: XMPP_SERVER
              value: localhost
            - name: DOCKER_HOST_ADDRESS
              value: HOST_IP_ADDRESS
            - name: XMPP_DOMAIN
              value: meet.jitsi
            - name: ENABLE_GUESTS
              value: "1"
            - name: XMPP_GUEST_DOMAIN
              value: guest.meet.jitsi
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.jitsi
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.jitsi
            - name: JVB_STUN_SERVERS
              value: stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "true"
            - name: JVB_AUTH_USER
              value: jvb
            - name: JVB_PORT
              value: "30300"
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JVB_AUTH_PASSWORD
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_AUTH_PASSWORD
            - name: JVB_BREWERY_MUC
              value: jvbbrewery
            - name: TZ
              value: Europe/Rome
```

I'd suggest you to start from the third option. Could you provide me a feedback after?
