### ISSUE TITLE
Guest Access Does Not Work With LDAP Authentication Method On Kubernetes (Rancher)

### ISSUE THREAD

**Issue by rojenzaman** [jitsi/docker-jitsi-meet#790]
I did implement this [kubernetes method](https://github.com/jitsi/docker-jitsi-meet/tree/master/examples/kubernetes) to Rancher.
That is correctly works, not have any problem.

Also I activated LDAP authentication method, It is work too. But it has a problem.

**Problem:**
When the LDAP user creates a room, the guest user cannot access this room.

I enabled  **ENABLE_GUESTS** and setted **XMPP_GUEST_DOMAIN**.

### Note:
The **Jitsi Documantation** [say](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker#advanced-configuration) those values are default for containers as internal network:
```text
XMPP_DOMAIN                meet.jitsi
XMPP_AUTH_DOMAIN           auth.meet.jitsi
XMPP_SERVER                xmpp.meet.jitsi
XMPP_BOSH_URL_BASE         http://xmpp.meet.jitsi:5280
XMPP_MUC_DOMAIN            muc.meet.jitsi
XMPP_INTERNAL_MUC_DOMAIN   internal-muc.meet.jitsi
XMPP_GUEST_DOMAIN          guest.meet.jitsi
```
so I used those.

## CONFIGURATIONS

Here is prosody config lines for guest domain after deploy:

```conf
# cat /config/conf.d/jitsi-meet.cfg.lua | grep -A3 'guest.meet.jitsi'
VirtualHost "guest.meet.jitsi"
    authentication = "anonymous"
    c2s_require_encryption = false
```

**deployment.yaml** ENV values for the **jitsi prosody container**:
```yaml
- name: prosody
  image: jitsi/prosody
  imagePullPolicy: Always
  env:
    - name: ENABLE_AUTH
      value: "1"
    - name: ENABLE_GUESTS
      value: "1"
    - name: AUTH_TYPE
      value: ldap         
    - name: LDAP_URL
      value: ldap://ldap.mydomain.com:389
    - name: LDAP_BASE
      value: DC=mydomain    
    - name: LDAP_BINDDN
      value: cn=rouser,dc=mydomain 
    - name: LDAP_BINDPW
      valueFrom:
        secretKeyRef:
          name: jitsi-config
          key: LDAP_BINDPW                                    
    - name: LDAP_AUTH_METHOD
      value: bind           
    - name: LDAP_VERSION
      value: "3"
    - name: LDAP_USE_TLS
      value: "0"
    - name: LDAP_START_TLS
      value: "0"
    - name: XMPP_DOMAIN
      value: meet.jitsi
    - name: XMPP_AUTH_DOMAIN
      value: auth.meet.jitsi
    - name: XMPP_GUEST_DOMAIN
      value: guest.meet.jitsi              
    - name: XMPP_MUC_DOMAIN
      value: muc.meet.jitsi
    - name: XMPP_INTERNAL_MUC_DOMAIN
      value: internal-muc.meet.jitsi
    - name: JICOFO_COMPONENT_SECRET
      valueFrom:
        secretKeyRef:
          name: jitsi-config
          key: JICOFO_COMPONENT_SECRET
    - name: JVB_AUTH_USER
      value: jvb
    - name: JVB_AUTH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: jitsi-config
          key: JVB_AUTH_PASSWORD
    - name: JICOFO_AUTH_USER
      value: focus
    - name: JICOFO_AUTH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: jitsi-config
          key: JICOFO_AUTH_PASSWORD
    - name: TZ
      value: Europe/Istanbul
    - name: JVB_TCP_HARVESTER_DISABLED
      value: "true"
```

**deployment.yaml** ENV values for the **jitsi web container**:

```yaml
- name: web
  image: jitsi/web
  imagePullPolicy: Always
  env:
    - name: XMPP_SERVER
      value: localhost
    - name: JICOFO_AUTH_USER
      value: focus
    - name: XMPP_DOMAIN
      value: meet.jitsi
    - name: XMPP_AUTH_DOMAIN
      value: auth.meet.jitsi
    - name: XMPP_INTERNAL_MUC_DOMAIN
      value: internal-muc.meet.jitsi
    - name: XMPP_BOSH_URL_BASE
      value: http://127.0.0.1:5280
    - name: XMPP_MUC_DOMAIN
      value: muc.meet.jitsi
    - name: TZ
      value: Europe/Istanbul
    - name: JVB_TCP_HARVESTER_DISABLED
      value: "true"
```
**deployment.yaml** ENV values for the **jvb container**:

```text
env:
  - name: XMPP_SERVER
    value: localhost
  - name: DOCKER_HOST_ADDRESS
    value: 192.168.10.20
  - name: XMPP_DOMAIN
    value: meet.jitsi
  - name: XMPP_AUTH_DOMAIN
    value: auth.meet.jitsi
  - name: XMPP_INTERNAL_MUC_DOMAIN
    value: internal-muc.meet.jitsi
  - name: JVB_STUN_SERVERS
    value: stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302
  - name: JICOFO_AUTH_USER
    value: focus
  - name: JVB_TCP_HARVESTER_DISABLED
    value: "true"
  - name: JVB_AUTH_USER
    value: jvb
  - name: JVB_PORT
    value: "30300"
  - name: JVB_AUTH_PASSWORD
    valueFrom:
      secretKeyRef:
        name: jitsi-config
        key: JVB_AUTH_PASSWORD
  - name: JICOFO_AUTH_PASSWORD
    valueFrom:
      secretKeyRef:
        name: jitsi-config
        key: JICOFO_AUTH_PASSWORD
  - name: JVB_BREWERY_MUC
    value: jvbbrewery
  - name: TZ
    value: Europe/Istanbul
```

**deployment.yaml** ENV values for the **jicofo container** :

```text
env:
  - name: XMPP_SERVER
    value: localhost
  - name: XMPP_DOMAIN
    value: meet.jitsi
  - name: XMPP_AUTH_DOMAIN
    value: auth.meet.jitsi
  - name: XMPP_INTERNAL_MUC_DOMAIN
    value: internal-muc.meet.jitsi
  - name: JICOFO_COMPONENT_SECRET
    valueFrom:
      secretKeyRef:
        name: jitsi-config
        key: JICOFO_COMPONENT_SECRET
  - name: JICOFO_AUTH_USER
    value: focus
  - name: JICOFO_AUTH_PASSWORD
    valueFrom:
      secretKeyRef:
        name: jitsi-config
        key: JICOFO_AUTH_PASSWORD
  - name: TZ
    value: Europe/Istanbul
  - name: JVB_BREWERY_MUC
    value: jvbbrewery
```

**saslauthd.conf** file after deploy:

```conf
# cat /etc/saslauthd.conf 

ldap_servers: ldap://ldap.mydomain.com:389
ldap_search_base: DC=mydomain

ldap_bind_dn: cn=rouser,dc=mydomain
ldap_bind_pw: *********************

ldap_filter: uid=%u
ldap_version: 3
ldap_auth_method: bind
```
**Web-service.yaml** file:

```text
apiVersion: v1
kind: Service
metadata:
  labels:
    service: web
  name: web
  namespace: jitsi
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  - name: "https"
    port: 443
    targetPort: 443
  selector:
    k8s-app: jitsi
---
 apiVersion: networking.k8s.io/v1beta1
 kind: Ingress
 metadata:
   name: jitsi
   namespace: jitsi
 spec:
  rules:
  - host: jitsi.mydomain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: http
```

**Jvb-service.yaml** file:

```text
apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb
  name: jvb-udp
  namespace: jitsi
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
  - port: 30300
    protocol: UDP
    targetPort: 30300
    nodePort: 30300
  selector:
    k8s-app: jitsi
```

**Secret values**:

```text
JICOFO_AUTH_PASSWORD 	 ********	 	  	
JICOFO_COMPONENT_SECRET  ******** 		 	  	
JVB_AUTH_PASSWORD 		 ********
LDAP_BINDPW              ********
```

### prosody log:

```text
10/16/2020 11:43:14 AM  saslauthd[256] :released accept lock
10/16/2020 11:43:14 AM  saslauthd[275] :acquired accept lock
10/16/2020 11:43:14 AM  saslauthd[256] :attempting a read lock on slot: 1305
10/16/2020 11:43:14 AM  saslauthd[256] :[login=ldapuser] [service=xmpp] [realm=meet.jitsi]: found with valid passwd
10/16/2020 11:43:14 AM  saslauthd[256] :attempting to release lock on slot: 1305
10/16/2020 11:43:14 AM  saslauthd[256] :auth success (cached): [user=ldapuser] [service=xmpp] 10/16/2020 11:43:14 AM  [realm=meet.jitsi]
10/16/2020 11:43:14 AM  saslauthd[256] :response: OK
10/16/2020 11:43:14 AM  bosh625b28bb-4ca9-4ca2-9e04-605df49fd403                     info	Authenticated as ldapuser@meet.jitsi    #end of ldap user log
10/16/2020 11:45:39 AM  mod_bosh                                                     info	New BOSH session, assigned it sid '0956b0da-c94d-462e-a024-a4a78b6dfd7a'   #guest acess log here
10/16/2020 11:45:39 AM  bosh0956b0da-c94d-462e-a024-a4a78b6dfd7a                     info	BOSH client disconnected: session close      #guest access log here
```

### web container log at the same time:

```text
10.10.9.0 - - [16/Oct/2020:11:43:14 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 545 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
10.10.0.0 - - [16/Oct/2020:11:43:14 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 199 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.10.20 - - [16/Oct/2020:11:43:14 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 554 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
10.10.9.0 - - [16/Oct/2020:11:43:15 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 307 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
10.10.0.0 - - [16/Oct/2020:11:43:15 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 247 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.10.20 - - [16/Oct/2020:11:43:15 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 3049 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
10.10.9.0 - - [16/Oct/2020:11:43:15 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 492 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
10.10.0.0 - - [16/Oct/2020:11:43:16 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 2060 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.10.20 - - [16/Oct/2020:11:43:16 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 3230 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
10.10.9.0 - - [16/Oct/2020:11:43:16 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 1325 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
10.10.0.0 - - [16/Oct/2020:11:43:16 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 1325 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.10.20 - - [16/Oct/2020:11:43:25 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 293 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
10.10.9.0 - - [16/Oct/2020:11:43:35 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 293 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
10.10.0.0 - - [16/Oct/2020:11:43:45 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 293 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.10.20 - - [16/Oct/2020:11:43:55 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 293 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
10.10.9.0 - - [16/Oct/2020:11:44:05 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 293 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
10.10.0.0 - - [16/Oct/2020:11:44:15 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 293 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.10.20 - - [16/Oct/2020:11:44:25 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 293 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
10.10.9.0 - - [16/Oct/2020:11:44:35 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 293 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
10.10.0.0 - - [16/Oct/2020:11:44:45 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 293 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.10.20 - - [16/Oct/2020:11:44:55 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 293 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
10.10.9.0 - - [16/Oct/2020:11:45:05 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 293 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
10.10.0.0 - - [16/Oct/2020:11:45:15 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 293 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.10.20 - - [16/Oct/2020:11:45:25 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 293 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
10.10.0.0 - - [16/Oct/2020:11:45:30 +0300] "GET /images/jitsilogo.png?v=1 HTTP/1.1" 200 3376 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.10.20 - - [16/Oct/2020:11:45:30 +0300] "GET /favicon.ico HTTP/1.1" 200 3638 "http://jitsi.mydomain.com/images/jitsilogo.png?v=1" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
10.10.9.0 - - [16/Oct/2020:11:45:35 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 293 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.10.20 - - [16/Oct/2020:11:45:36 +0300] "GET /testroom HTTP/1.1" 200 18312 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
10.10.9.0 - - [16/Oct/2020:11:45:36 +0300] "GET /libs/do_external_connect.min.js?v=1 HTTP/1.1" 200 1173 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
192.168.10.20 - - [16/Oct/2020:11:45:36 +0300] "GET /libs/lib-jitsi-meet.min.js?v=4428 HTTP/1.1" 200 228858 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
10.10.9.0 - - [16/Oct/2020:11:45:37 +0300] "GET /libs/app.bundle.min.js?v=4428 HTTP/1.1" 200 1382306 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
192.168.10.20 - - [16/Oct/2020:11:45:39 +0300] "GET /sounds/rejected.wav HTTP/1.1" 206 69236 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
10.10.9.0 - - [16/Oct/2020:11:45:39 +0300] "GET /sounds/rejected.wav HTTP/1.1" 206 69236 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
192.168.10.20 - - [16/Oct/2020:11:45:39 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 545 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
10.10.9.0 - - [16/Oct/2020:11:45:39 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 116 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
10.10.0.0 - - [16/Oct/2020:11:45:47 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 293 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.10.20 - - [16/Oct/2020:11:45:57 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 293 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
10.10.9.0 - - [16/Oct/2020:11:46:07 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 293 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
10.10.0.0 - - [16/Oct/2020:11:46:17 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 293 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.10.20 - - [16/Oct/2020:11:46:28 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 293 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
10.10.9.0 - - [16/Oct/2020:11:46:38 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 293 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
10.10.0.0 - - [16/Oct/2020:11:46:48 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 293 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
192.168.10.20 - - [16/Oct/2020:11:46:59 +0300] "POST /http-bind?room=testroom HTTP/1.1" 200 293 "http://jitsi.mydomain.com/testroom" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
```

### Jitsi video bridge container log:

```text
Oct 16, 2020 11:45:03 AM org.jitsi.utils.logging2.LoggerImpl log
INFO: create_conf, id=739fd1437f690cd4 gid=-1 logging=false
Oct 16, 2020 11:45:03 AM org.jitsi.utils.logging2.LoggerImpl log
INFO: Performed a successful health check in PT0.003S. Sticky failure: false
Oct 16, 2020 11:45:13 AM org.jitsi.utils.logging2.LoggerImpl log
INFO: create_conf, id=561f3df4a6efc5b2 gid=-1 logging=false
Oct 16, 2020 11:45:13 AM org.jitsi.utils.logging2.LoggerImpl log
INFO: Performed a successful health check in PT0.011S. Sticky failure: false
Oct 16, 2020 11:45:22 AM org.jitsi.utils.logging2.LoggerImpl log
INFO: Running expire()
Oct 16, 2020 11:45:23 AM org.jitsi.utils.logging2.LoggerImpl log
INFO: create_conf, id=7c26017d5bd00449 gid=-1 logging=false
Oct 16, 2020 11:45:23 AM org.jitsi.utils.logging2.LoggerImpl log
INFO: Performed a successful health check in PT0.003S. Sticky failure: false
Oct 16, 2020 11:45:33 AM org.jitsi.utils.logging2.LoggerImpl log
INFO: create_conf, id=2e89a5c6321160a6 gid=-1 logging=false
Oct 16, 2020 11:45:33 AM org.jitsi.utils.logging2.LoggerImpl log
INFO: Performed a successful health check in PT0.003S. Sticky failure: false
Oct 16, 2020 11:45:43 AM org.jitsi.utils.logging2.LoggerImpl log
INFO: create_conf, id=2e7dc8163b7a0ca1 gid=-1 logging=false
Oct 16, 2020 11:45:43 AM org.jitsi.utils.logging2.LoggerImpl log
INFO: Performed a successful health check in PT0.011S. Sticky failure: false
Oct 16, 2020 11:45:53 AM org.jitsi.utils.logging2.LoggerImpl log
INFO: create_conf, id=bddf0e95bbb2852f gid=-1 logging=false
Oct 16, 2020 11:45:53 AM org.jitsi.utils.logging2.LoggerImpl log
INFO: Performed a successful health check in PT0.003S. Sticky failure: false
```

### Jicofo container log:

```text
Jicofo 2020-10-16 11:43:15.551 INFO: [73] org.jitsi.jicofo.xmpp.FocusComponent.log() Focus request for room: testroom@muc.meet.jitsi
Jicofo 2020-10-16 11:43:15.552 INFO: [73] org.jitsi.jicofo.FocusManager.log() Created new focus for testroom@muc.meet.jitsi@auth.meet.jitsi. Conference count 1,options: channelLastN=-1 enableLipSync=false startAudioMuted=10 stereo=false enableTcc=true startVideoMuted=10 enableRemb=true openSctp=false disableRtx=false
Jicofo 2020-10-16 11:43:15.552 INFO: [73] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Joining the room: testroom@muc.meet.jitsi
Jicofo 2020-10-16 11:43:16.081 INFO: [28] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberJoined sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@22a591e1 member=ChatMember[testroom@muc.meet.jitsi/45073391, jid: null]@353774756]
Jicofo 2020-10-16 11:43:16.084 INFO: [28] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Granted owner to testroom@muc.meet.jitsi/45073391
Jicofo 2020-10-16 11:43:16.085 INFO: [28] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member testroom@muc.meet.jitsi/45073391 joined.
```
<br>

**Why is Guest Access not working? I tried a lot way but could not solve it.**
