### ISSUE TITLE
No audio, only video on calls

### ISSUE THREAD

**Issue by bkraul** [jitsi/docker-jitsi-meet#85]
I have a weird issue with a docker instance set up using the compose found in this repository. The stack works (starts) perfectly, and on ocassion, both HD video and audio work flawlessly. However, on most cases, guests can see me and hear me fine, and  I can see them, but I cannot hear them at all. We have tried all we can in order to rule out an audio configuration issue on their end. 

We have also tried this in a LAN setting in order to rule out any ports issues, and the result is the same. Any ideas as to why this would be happening?

**Comment by bkraul** [comment]
I am seeing this on the jicofo log:
```
Not merging A/V streams from ....
```

**Comment by bkraul** [comment]
Here is my compose. I am *not* using an .env file for diagnostic purposesa the moment, so everything used is in the compose file. The only variant is I am behind jwilder/nginx-proxy setup (through bridged network `reverse-proxy` which works perfectly. Port `10000` and `4443` are running as host ports like it is on the original compose.

```yml
version: '3.2'
services:
  # Frontend
  web:
    image: jitsi/web
    volumes:
      - /root/docker-persist/jitsi/web:/config
    environment:
      - VIRTUAL_HOST=jitsy.mydomain.com
      - VIRTUAL_PORT=80
      - ENABLE_AUTH=1
      - ENABLE_GUESTS=1
      - ENABLE_LETSENCRYPT=0
      - ENABLE_HTTP_REDIRECT=0
      - DISABLE_HTTPS=1
      - JICOFO_AUTH_USER=focus
      - LETSENCRYPT_DOMAIN=
      - LETSENCRYPT_EMAIL=
      - XMPP_DOMAIN=meet.jitsi
      - XMPP_AUTH_DOMAIN=auth.meet.jitsi
      - XMPP_BOSH_URL_BASE=http://xmpp.meet.jitsi:5280
      - XMPP_GUEST_DOMAIN=guest.meet.jitsi
      - XMPP_MUC_DOMAIN=muc.meet.jitsi
      - TZ=America/Chicago
    networks:
      - meet.jitsi
      - reverse-proxy

  # XMPP server
  prosody:
    image: jitsi/prosody
    expose:
      - '5222'
      - '5347'
      - '5280'
    volumes:
      - /root/docker-persist/jitsi/prosody:/config
    environment:
      - ENABLE_AUTH=1
      - ENABLE_GUESTS=1
      - XMPP_DOMAIN=meet.jitsi
      - XMPP_AUTH_DOMAIN=auth.meet.jitsi
      - XMPP_GUEST_DOMAIN=guest.meet.jitsi
      - XMPP_MUC_DOMAIN=muc.meet.jitsi
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
      - XMPP_MODULES=
      - XMPP_MUC_MODULES=
      - XMPP_INTERNAL_MUC_MODULES=
      - JICOFO_COMPONENT_SECRET=s3cr37
      - JICOFO_AUTH_USER=focus
      - JICOFO_AUTH_PASSWORD=passw0rd
      - JVB_AUTH_USER=jvb
      - JVB_AUTH_PASSWORD=passw0rd
      - JIGASI_XMPP_USER=jigasi
      - JIGASI_XMPP_PASSWORD=passw0rd
      - TZ=America/Chicago
    networks:
      meet.jitsi:
        aliases:
          - xmpp.meet.jitsi

  # Focus component
  jicofo:
    image: jitsi/jicofo
    volumes:
      - /root/docker-persist/jitsi/jicofo:/config
    environment:
      - ENABLE_AUTH=1
      - XMPP_DOMAIN=meet.jitsi
      - XMPP_AUTH_DOMAIN=auth.meet.jitsi
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
      - XMPP_SERVER=xmpp.meet.jitsi
      - JICOFO_COMPONENT_SECRET=s3cr37
      - JICOFO_AUTH_USER=focus
      - JICOFO_AUTH_PASSWORD=passw0rd
      - JVB_BREWERY_MUC=jvbbrewery
      - JIGASI_BREWERY_MUC=jigasibrewery
      - TZ=America/Chicago
    depends_on:
      - prosody
    networks:
      meet.jitsi:

  # Video bridge
  jvb:
    image: jitsi/jvb
    ports:
      - '10000:10000/udp'
      - '4443:4443'
    volumes:
      - /root/docker-persist/jitsi/jvb:/config
    environment:
      - DOCKER_HOST_ADDRESS=10.10.10.127
      - XMPP_AUTH_DOMAIN=auth.meet.jitsi
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
      - XMPP_SERVER=xmpp.meet.jitsi
      - JVB_AUTH_USER=jvb
      - JVB_AUTH_PASSWORD=passw0rd
      - JVB_BREWERY_MUC=jvbbrewery
      - JVB_PORT=10000
      - JVB_TCP_HARVESTER_DISABLED=true
      - JVB_TCP_PORT=4443
      - JVB_STUN_SERVERS=stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302
      - JVB_ENABLE_APIS=rest,colibri
      - JICOFO_AUTH_USER=focus
      - TZ=America/Chicago
    depends_on:
      - prosody
    networks:
      meet.jitsi:

# Custom network so all services can communicate using a FQDN
networks:
  meet.jitsi:
  reverse-proxy:
    external:
      name: reverse-proxy

```
