### ISSUE TITLE
etherpad prints warning after opening

### ISSUE THREAD

**Issue by tele-tom** [jitsi/docker-jitsi-meet#911]
stable-5142-4: release

After opening shared document the following warning is printed on the top of the page after the Welcome Text:
`Warning: DirtyDB is used. This is fine for testing but not recommended for production. -- To suppress these warning messages change suppressErrorsInPadText to true in your settings.json`

**Comment by prayagsingh** [comment]
In order to suppress these warnings, you have to use DB like postgres, mariadb etc. please refer to etherpad-lite github page.

**Comment by tele-tom** [comment]
Thx

**Comment by Perdu** [comment]
Full answer:
Here's how I modified `etherpad.yml` to do that:
```
version: '3'
services:
    # Etherpad: real-time collaborative document editing
    db:
        image: mysql:5.7
        restart: ${RESTART_POLICY}
        environment:
            - MYSQL_DATABASE=etherpad_lite_db
            - MYSQL_PASSWORD=CHANGEME
            - MYSQL_USER=etherpaduser
        volumes:
            - ./etherpad/db/mysql/data:/var/lib/mysql
            - ./etherpad/db/mysql/init:/docker-entrypoint-initdb.d/:ro
        networks:
            - meet.jitsi
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    etherpad:
        image: etherpad/etherpad:1.8.6
        restart: ${RESTART_POLICY}
        environment:
            - TITLE=${ETHERPAD_TITLE}
            - DEFAULT_PAD_TEXT=${ETHERPAD_DEFAULT_PAD_TEXT}
            - SKIN_NAME=${ETHERPAD_SKIN_NAME}
            - SKIN_VARIANTS=${ETHERPAD_SKIN_VARIANTS}
            - DB_TYPE=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_NAME=etherpad_lite_db
            - DB_USER=etherpaduser
            - DB_PASS=CHANGEME
            - DB_CHARSET=utf8mb4
        networks:
            meet.jitsi:
                aliases:
                    - etherpad.meet.jitsi
        ports:
            - 9001:9001
```
And I added the database creation code in described [on etherpad-lite's wiki](https://github.com/ether/etherpad-lite/wiki/How-to-use-Etherpad-Lite-with-MySQL) in `etherpad/db/mysql/init/schema.sql`:
```
CREATE TABLE `store` (
  `key` varchar(100) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  `value` longtext COLLATE utf8mb4_bin NOT NULL,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
```
Also, make sure you have the right permissions on `etherpad/db/mysql/data/` and `etherpad/db/mysql/init/`.

Other solutions exist using a different etherpad image, e.g. [here](https://github.com/uni-halle/etherpad-lite-docker) or [here](https://github.com/Schuermi7/etherpad-mysql-docker).

By the way, shouldn't this be integrated as the default option on this repository, rather than using a db not recommended for production?
