### ISSUE TITLE
Jicofo crashes since last update

### ISSUE THREAD

**Issue by Twilek-de** [jitsi/docker-jitsi-meet#923]
I just updated to the latest release. When I try to spin up Jitsi Meet, I get an
```
jicofo_1   | Jicofo 2021-01-29 19:52:23.273 SEVERE: [1] org.jitsi.jicofo.Main.log() An uncaught exception occurred in thread=Thread[main,5,main]
jicofo_1   | org.jitsi.cmd.ParseException: Some of required arguments were not specified: [secret]
jicofo_1   |    at org.jitsi.cmd.CmdLine.parse(CmdLine.java:130)
jicofo_1   |    at org.jitsi.jicofo.Main.setSystemProperties(Main.java:182)
jicofo_1   |    at org.jitsi.jicofo.Main.main(Main.java:56)
```

every couple of seconds and Jitsi won´t work.

I tried resetting the config but I can´t get rid of the error.

**Comment by prayagsingh** [comment]
You have to configure all the new env variables in docker-compose.yaml file. They aren't added to env.example file. Please configure them. Below is the snippet. Please try this config and let me know if its work. 
```
            # enable/disable video codec
            ENABLE_CODEC_VP8: "true"
            ENABLE_CODEC_VP9: "true"
            ENABLE_CODEC_H264: "false"
            # Bridge config
            MAX_BRIDGE_PARTICIPANTS:
            BRIDGE_AVG_PARTICIPANT_STRESS:
            MAX_BRIDGE_PARTICIPANTS:
            OCTO_BRIDGE_SELECTION_STRATEGY: SingleBridgeSelectionStrategy
            # Bridge healthcheck
            JICOFO_ENABLE_BRIDGE_HEALTH_CHECKS: "true"
            # conference config
            ENABLE_AUTO_OWNER: "false"
            JICOFO_CONF_INITIAL_PARTICIPANT_WAIT_TIMEOUT:
            JICOFO_CONF_SINGLE_PARTICIPANT_TIMEOUT:
            # internal healthcheck
            JICOFO_ENABLE_HEALTH_CHECKS: "false"
            # enable recording
            ENABLE_RECORDING: 1
            JIBRI_REQUEST_RETRIES:
            # jibri-sip
            ENABLE_JIBRI_SIP: 0
            # jigasi
            JIGASI_BREWERY_MUC:
            JICOFO_SHORT_ID: 1
            # enable sctp
            ENABLE_SCTP: "false"
            JICOFO_SHORT_ID: 1
            AUTH_TYPE: internal
            ENABLE_AUTH: 0
            JICOFO_COMPONENT_SECRET: << UPDATE PASSWORD >>
            JICOFO_AUTH_USER: focus
            JICOFO_AUTH_PASSWORD: << UPDATE PASSWORD >>
            JICOFO_RESERVATION_REST_BASE_URL:
            XMPP_DOMAIN: meet.jitsi
            XMPP_AUTH_DOMAIN: auth.meet.jitsi
            XMPP_INTERNAL_MUC_DOMAIN: internal-muc.meet.jitsi
            XMPP_SERVER: xmpp.meet.jitsi
            XMPP_MUC_DOMAIN: muc.meet.jitsi
            TZ: Asia/Kolkata
            JIBRI_BREWERY_MUC: jibribrewery
            JIBRI_PENDING_TIMEOUT: 90
            JVB_BREWERY_MUC: jvbbrewery
            JIGASI_BREWERY_MUC: jigasibrewery
            
```
