### ISSUE TITLE
Consider adding a general stable tag for people to upgrade automatically

### ISSUE THREAD

**Issue by GammaPi** [jitsi/docker-jitsi-meet#983]
Currently, stable versions are split into different tags. This is difficult for automatic upgrade.
What's the consideration behind such design?

**Comment by saghul** [comment]
"latest" used to be that, and it didn't work out.

Better to avoid surprises, updating is simple, all one needs is the compose file.

**Comment by stoically** [comment]
> and it didn't work out.

Didn't work out for whom? My personal use self-hosting setup is geared towards "prefer automatic updating and potentially breaking over getting outdated and exploited", and most docker things I use have some sort of stable tag (`nextcloud:latest`) or stable version (e.g. `gitea:1`). Would be really nice if you could reconsider the decision.

**Comment by saghul** [comment]
latest still exists.

**Comment by stoically** [comment]
but `latest` is `HEAD` and not latest stable release, or am I mistaken?

**Comment by stoically** [comment]
I guess what I'm actually asking for (and what the issue was about) is a general `stable` git tag, since updating also means keeping the `docker-compose.yml` updated, which you currently have to do manually. And you can't really point the `docker-compose.yml` to another docker hub tag without losing automatic update capabilities

**Comment by stoically** [comment]
Though, I just realized, I could simply parse the `tag_name` from https://api.github.com/repos/jitsi/docker-jitsi-meet/releases/latest and update based on that. That works

**Comment by saghul** [comment]
Each stable release is also pushed as latest. Nightlies are pushed to unstable but not latest.

**Comment by stoically** [comment]
Thanks for the clarification.

But that doesn't help if you want to stay on the stable `docker-compose.yml`, right? I suppose the only way to automatically update that is https://github.com/jitsi/docker-jitsi-meet/issues/983#issuecomment-821965866?

**Comment by saghul** [comment]
Correct.

**Comment by stoically** [comment]
Just for reference, those Ansible tasks do the trick for me

```yaml
- name: "jitsi-meet: get latest release json"
  uri:
    url: https://api.github.com/repos/jitsi/docker-jitsi-meet/releases/latest
    return_content: yes
  register: jitsi_meet_latest_release

- name: "jitsi-meet: get current checked out tag"
  shell: git tag --points-at HEAD
  args:
    chdir: "{{ jitsi_meet_dir }}"
  register: jitsi_meet_current_release

- name: "jitsi-meet: upgrade"
  shell: git checkout "{{ jitsi_meet_latest_release.json.tag_name }}" && docker-compose up -d
  args:
    chdir: "{{ jitsi_meet_dir }}"
  when: jitsi_meet_latest_release.json.tag_name != jitsi_meet_current_release.stdout
```
